// GENERATED by scripts/generate-api-routes.mjs — do not edit.
//
// The route table for the standalone API Worker. Each entry points at the SAME
// module `app/api/**/route.ts` that the Next app serves, so there is one copy
// of every handler and no possibility of the two surfaces disagreeing.
//
// Regenerate with `pnpm api:routes`. CI runs `pnpm api:routes:check`, which
// fails if a route was added to the app without appearing here.

import type { RouteModule } from "./router";

export type GeneratedRoute = {
  /** URL pattern, `:name` for a dynamic segment. */
  readonly pattern: string;
  /** HTTP methods the module exports. */
  readonly methods: readonly string[];
  /** Loads the route module. */
  readonly load: () => Promise<RouteModule>;
};

/** 36 routes, ordered so a literal segment is matched before a parameter. */
export const ROUTES: readonly GeneratedRoute[] = [
  {
    pattern: "/api/v1/architecture/frontend/axes",
    methods: ["GET"],
    load: () => import("../../app/api/v1/architecture/frontend/axes/route"),
  },
  {
    pattern: "/api/v1/architecture/frontend/layers",
    methods: ["GET"],
    load: () => import("../../app/api/v1/architecture/frontend/layers/route"),
  },
  {
    pattern: "/api/v1/ai/instructions/:name",
    methods: ["GET"],
    load: () => import("../../app/api/v1/ai/instructions/[name]/route"),
  },
  {
    pattern: "/api/v1/architecture/layers/:n",
    methods: ["GET"],
    load: () => import("../../app/api/v1/architecture/layers/[n]/route"),
  },
  {
    pattern: "/api/v1/architecture/nodes/:n",
    methods: ["GET"],
    load: () => import("../../app/api/v1/architecture/nodes/[n]/route"),
  },
  {
    pattern: "/api/v1/ui/:name/docs",
    methods: ["GET"],
    load: () => import("../../app/api/v1/ui/[name]/docs/route"),
  },
  {
    pattern: "/api/v1/ui/:name/versions",
    methods: ["GET"],
    load: () => import("../../app/api/v1/ui/[name]/versions/route"),
  },
  {
    pattern: "/api/v1/ai/instructions",
    methods: ["GET"],
    load: () => import("../../app/api/v1/ai/instructions/route"),
  },
  {
    pattern: "/api/v1/architecture/axes",
    methods: ["GET"],
    load: () => import("../../app/api/v1/architecture/axes/route"),
  },
  {
    pattern: "/api/v1/skills/summary",
    methods: ["GET"],
    load: () => import("../../app/api/v1/skills/summary/route"),
  },
  {
    pattern: "/api/v1/ubuntu/pillars",
    methods: ["GET"],
    load: () => import("../../app/api/v1/ubuntu/pillars/route"),
  },
  {
    pattern: "/api/v1/ubuntu/principles",
    methods: ["GET"],
    load: () => import("../../app/api/v1/ubuntu/principles/route"),
  },
  {
    pattern: "/api/v1/changelog/:version",
    methods: ["GET"],
    load: () => import("../../app/api/v1/changelog/[version]/route"),
  },
  {
    pattern: "/api/v1/docs/:slug",
    methods: ["GET"],
    load: () => import("../../app/api/v1/docs/[slug]/route"),
  },
  {
    pattern: "/api/v1/rs/:name",
    methods: ["GET"],
    load: () => import("../../app/api/v1/rs/[name]/route"),
  },
  {
    pattern: "/api/v1/samples/:type",
    methods: ["GET"],
    load: () => import("../../app/api/v1/samples/[type]/route"),
  },
  {
    pattern: "/api/v1/skills/:name",
    methods: ["GET"],
    load: () => import("../../app/api/v1/skills/[name]/route"),
  },
  {
    pattern: "/api/v1/ui/:name",
    methods: ["GET"],
    load: () => import("../../app/api/v1/ui/[name]/route"),
  },
  {
    pattern: "/api/v1/architecture",
    methods: ["GET"],
    load: () => import("../../app/api/v1/architecture/route"),
  },
  {
    pattern: "/api/v1/brand",
    methods: ["GET"],
    load: () => import("../../app/api/v1/brand/route"),
  },
  {
    pattern: "/api/v1/changelog",
    methods: ["GET"],
    load: () => import("../../app/api/v1/changelog/route"),
  },
  {
    pattern: "/api/v1/data-layer",
    methods: ["GET"],
    load: () => import("../../app/api/v1/data-layer/route"),
  },
  {
    pattern: "/api/v1/docs",
    methods: ["GET"],
    load: () => import("../../app/api/v1/docs/route"),
  },
  {
    pattern: "/api/v1/ecosystem",
    methods: ["GET"],
    load: () => import("../../app/api/v1/ecosystem/route"),
  },
  {
    pattern: "/api/v1/health",
    methods: ["GET"],
    load: () => import("../../app/api/v1/health/route"),
  },
  {
    pattern: "/api/v1/pipeline",
    methods: ["GET"],
    load: () => import("../../app/api/v1/pipeline/route"),
  },
  {
    pattern: "/api/v1/samples",
    methods: ["GET"],
    load: () => import("../../app/api/v1/samples/route"),
  },
  {
    pattern: "/api/v1/search",
    methods: ["GET"],
    load: () => import("../../app/api/v1/search/route"),
  },
  {
    pattern: "/api/v1/skills",
    methods: ["GET"],
    load: () => import("../../app/api/v1/skills/route"),
  },
  {
    pattern: "/api/v1/sovereignty",
    methods: ["GET"],
    load: () => import("../../app/api/v1/sovereignty/route"),
  },
  {
    pattern: "/api/v1/stats",
    methods: ["GET", "OPTIONS"],
    load: () => import("../../app/api/v1/stats/route"),
  },
  {
    pattern: "/api/v1/ui",
    methods: ["GET"],
    load: () => import("../../app/api/v1/ui/route"),
  },
  {
    pattern: "/api/chaos/:name",
    methods: ["GET", "POST"],
    load: () => import("../../app/api/chaos/[name]/route"),
  },
  {
    pattern: "/api/health/:name",
    methods: ["GET"],
    load: () => import("../../app/api/health/[name]/route"),
  },
  {
    pattern: "/api/openapi",
    methods: ["GET", "OPTIONS"],
    load: () => import("../../app/api/openapi/route"),
  },
  {
    pattern: "/api/v1",
    methods: ["GET"],
    load: () => import("../../app/api/v1/route"),
  },
];
