// NYUCHI DESIGN TOKENS — N1
// Swift / SwiftUI — generated by scripts/sync-tokens.ts from
// lib/tokens/palette.source.ts, the canonical palette in this repo.
//
// Carries all 21 families: seven minerals, seven heritage tones and
// the seven experimental — the same set /v1/brand and the MCP serve.
//
// DO NOT EDIT BY HAND. Run `pnpm tokens:sync`; `pnpm tokens:verify`
// fails the build if this file drifts from the source.

import SwiftUI

public extension Color {
    // Seven African Minerals
    static let mziziCobaltDark  = Color(hex: "#00B0FF")
    static let mziziCobaltLight = Color(hex: "#0047AB")
    static let mziziTanzaniteDark  = Color(hex: "#B388FF")
    static let mziziTanzaniteLight = Color(hex: "#4B0082")
    static let mziziMalachiteDark  = Color(hex: "#64FFDA")
    static let mziziMalachiteLight = Color(hex: "#004D40")
    static let mziziGoldDark  = Color(hex: "#FFD740")
    static let mziziGoldLight = Color(hex: "#5D4037")
    static let mziziTerracottaDark  = Color(hex: "#E1B07E")
    static let mziziTerracottaLight = Color(hex: "#A0522D")
    static let mziziSodaliteDark  = Color(hex: "#3D5AFE")
    static let mziziSodaliteLight = Color(hex: "#283593")
    static let mziziCopperDark  = Color(hex: "#FF8A65")
    static let mziziCopperLight = Color(hex: "#BF5A36")

    // Seven Heritage Colors
    static let mziziIndigoDark  = Color(hex: "#7986CB")
    static let mziziIndigoLight = Color(hex: "#4527A0")
    static let mziziSavannaDark  = Color(hex: "#E5C158")
    static let mziziSavannaLight = Color(hex: "#8D6E1A")
    static let mziziBaobabDark  = Color(hex: "#A1887F")
    static let mziziBaobabLight = Color(hex: "#4E342E")
    static let mziziSunsetDark  = Color(hex: "#FF7043")
    static let mziziSunsetLight = Color(hex: "#D84315")
    static let mziziRiverDark  = Color(hex: "#4DD0E1")
    static let mziziRiverLight = Color(hex: "#006064")
    static let mziziHematiteDark  = Color(hex: "#90A4AE")
    static let mziziHematiteLight = Color(hex: "#546E7A")
    static let mziziKalahariDark  = Color(hex: "#E8D9B5")
    static let mziziKalahariLight = Color(hex: "#C9B589")

    // Seven Experimental tones
    static let mziziEmberDark  = Color(hex: "#DA8766")
    static let mziziEmberLight = Color(hex: "#843D20")
    static let mziziAcaciaDark  = Color(hex: "#93A528")
    static let mziziAcaciaLight = Color(hex: "#4D5615")
    static let mziziFernDark  = Color(hex: "#2CB42B")
    static let mziziFernLight = Color(hex: "#175E17")
    static let mziziLagoonDark  = Color(hex: "#2AAE9B")
    static let mziziLagoonLight = Color(hex: "#165B51")
    static let mziziStormDark  = Color(hex: "#7E9BE0")
    static let mziziStormLight = Color(hex: "#284CA6")
    static let mziziDuskDark  = Color(hex: "#BA87E2")
    static let mziziDuskLight = Color(hex: "#742AAD")
    static let mziziProteaDark  = Color(hex: "#DF7BB4")
    static let mziziProteaLight = Color(hex: "#932464")
}

public struct MziziSpacing {
    public static let xs: CGFloat = 4
    public static let sm: CGFloat = 8
    public static let md: CGFloat = 12
    public static let base: CGFloat = 16
    public static let lg: CGFloat = 24
    public static let xl: CGFloat = 32
}

public struct MziziRadius {
    public static let sm: CGFloat = 7
    public static let md: CGFloat = 12
    public static let lg: CGFloat = 14
    public static let xl: CGFloat = 17
    public static let full: CGFloat = 9999
}

public struct MziziFonts {
    public static let sans = "Noto Sans"
    public static let serif = "Noto Serif"
    public static let mono = "JetBrains Mono"
}
