# NYUCHI DESIGN TOKENS — N1
# Python — generated by scripts/sync-tokens.ts from
# lib/tokens/palette.source.ts, the canonical palette in this repo.
#
# Carries all 21 families: seven minerals, seven heritage tones and
# the seven experimental — the same set /v1/brand and the MCP serve.
#
# DO NOT EDIT BY HAND. Run `pnpm tokens:sync`; `pnpm tokens:verify`
# fails the build if this file drifts from the source.

from dataclasses import dataclass


@dataclass(frozen=True)
class MziziMinerals:
    """Seven African Minerals — the brand accents, dark and light themes."""
    COBALT_DARK: str = "#00B0FF"
    COBALT_LIGHT: str = "#0047AB"
    TANZANITE_DARK: str = "#B388FF"
    TANZANITE_LIGHT: str = "#4B0082"
    MALACHITE_DARK: str = "#64FFDA"
    MALACHITE_LIGHT: str = "#004D40"
    GOLD_DARK: str = "#FFD740"
    GOLD_LIGHT: str = "#5D4037"
    TERRACOTTA_DARK: str = "#E1B07E"
    TERRACOTTA_LIGHT: str = "#A0522D"
    SODALITE_DARK: str = "#3D5AFE"
    SODALITE_LIGHT: str = "#283593"
    COPPER_DARK: str = "#FF8A65"
    COPPER_LIGHT: str = "#BF5A36"


@dataclass(frozen=True)
class MziziHeritage:
    """Seven Heritage tones — atmospheric anchors, dark and light themes."""
    INDIGO_DARK: str = "#7986CB"
    INDIGO_LIGHT: str = "#4527A0"
    SAVANNA_DARK: str = "#E5C158"
    SAVANNA_LIGHT: str = "#8D6E1A"
    BAOBAB_DARK: str = "#A1887F"
    BAOBAB_LIGHT: str = "#4E342E"
    SUNSET_DARK: str = "#FF7043"
    SUNSET_LIGHT: str = "#D84315"
    RIVER_DARK: str = "#4DD0E1"
    RIVER_LIGHT: str = "#006064"
    HEMATITE_DARK: str = "#90A4AE"
    HEMATITE_LIGHT: str = "#546E7A"
    KALAHARI_DARK: str = "#E8D9B5"
    KALAHARI_LIGHT: str = "#C9B589"


@dataclass(frozen=True)
class MziziExperimental:
    """Seven Experimental tones — the heptagon, dark and light themes."""
    EMBER_DARK: str = "#DA8766"
    EMBER_LIGHT: str = "#843D20"
    ACACIA_DARK: str = "#93A528"
    ACACIA_LIGHT: str = "#4D5615"
    FERN_DARK: str = "#2CB42B"
    FERN_LIGHT: str = "#175E17"
    LAGOON_DARK: str = "#2AAE9B"
    LAGOON_LIGHT: str = "#165B51"
    STORM_DARK: str = "#7E9BE0"
    STORM_LIGHT: str = "#284CA6"
    DUSK_DARK: str = "#BA87E2"
    DUSK_LIGHT: str = "#742AAD"
    PROTEA_DARK: str = "#DF7BB4"
    PROTEA_LIGHT: str = "#932464"


@dataclass(frozen=True)
class MziziSpacing:
    """Spacing scale, in pixels."""
    XS: int = 4
    SM: int = 8
    MD: int = 12
    BASE: int = 16
    LG: int = 24
    XL: int = 32


@dataclass(frozen=True)
class MziziRadius:
    """Radius scale, in pixels. Derived from the 7px unit."""
    SM: int = 7
    MD: int = 12
    LG: int = 14
    XL: int = 17
    FULL: int = 9999


# ─── Roles (#484) ─── what a component names; the Mzizi pack's values.
# From lib/tokens/roles.source.ts. A brand pack maps the same roles to its own values.
@dataclass(frozen=True)
class MziziRolesLight:
    """Colour roles, light theme."""
    PRIMARY: str = "#546E7A"
    PRIMARY_FOREGROUND: str = "#FFFFFF"
    RING: str = "#0047AB"
    BRAND_ACCENT: str = "#546E7A"
    BRAND_ACCENT_FOREGROUND: str = "#FFFFFF"
    APP_ACCENT: str = "#546E7A"
    APP_ACCENT_FOREGROUND: str = "#FFFFFF"
    PITCH: str = "#FAFAFA"
    VOID: str = "#F8F8F7"
    BASE: str = "#F3F3F1"
    SURFACE: str = "#EEEEEC"
    CONTAINER: str = "#E5E4E1"
    OVERLAY: str = "#E0DFDC"
    RAISED: str = "#D6D5D1"
    SCRIM: str = "rgba(0, 0, 0, 0.4)"
    WASH: str = "#E3E5E4"
    MUTED: str = "#FAF9F5"
    TEXT_PRIMARY: str = "#373635"
    TEXT_SECONDARY: str = "#575655"
    TEXT_TERTIARY: str = "#797877"
    HERO_TEXT: str = "#FFFFFF"
    MUTED_FOREGROUND: str = "#575655"
    SUCCESS: str = "#004D40"
    WARNING: str = "#7A5C00"
    ERROR: str = "#B3261E"
    INFO: str = "#0047AB"
    NEUTRAL: str = "#55514B"
    OFFLINE: str = "#674C32"
    SYNCING: str = "#1C5962"
    DESTRUCTIVE_CONTAINER: str = "#FDEDED"
    STATUS_SUCCESS: str = "#004D40"
    STATUS_SUCCESS_CONTAINER: str = "#E0F2F1"
    STATUS_SUCCESS_ON_CONTAINER: str = "#00332B"
    STATUS_SUCCESS_TEXT: str = "#004D40"
    STATUS_WARNING: str = "#5D4037"
    STATUS_WARNING_CONTAINER: str = "#FFF8E1"
    STATUS_WARNING_ON_CONTAINER: str = "#3E2723"
    STATUS_WARNING_TEXT: str = "#5D4037"
    STATUS_INFO: str = "#0047AB"
    STATUS_INFO_CONTAINER: str = "#E3F2FD"
    STATUS_INFO_ON_CONTAINER: str = "#002966"
    STATUS_INFO_TEXT: str = "#0047AB"
    STATUS_DANGER: str = "#A0522D"
    STATUS_DANGER_CONTAINER: str = "#F5E6D3"
    STATUS_DANGER_ON_CONTAINER: str = "#5D2906"
    STATUS_DANGER_TEXT: str = "#844425"
    STATUS_PREMIUM: str = "#4B0082"
    STATUS_PREMIUM_CONTAINER: str = "#F3E5F5"
    STATUS_PREMIUM_ON_CONTAINER: str = "#2E004D"
    STATUS_PREMIUM_TEXT: str = "#4B0082"
    STATUS_NEUTRAL: str = "#55514B"
    STATUS_NEUTRAL_CONTAINER: str = "#E5E4E1"
    STATUS_NEUTRAL_ON_CONTAINER: str = "#373635"
    STATUS_NEUTRAL_TEXT: str = "#575655"
    STATUS_STABLE: str = "#004D40"
    STATUS_STABLE_CONTAINER: str = "#E0F2F1"
    STATUS_STABLE_ON_CONTAINER: str = "#00332B"
    STATUS_STABLE_TEXT: str = "#004D40"
    STATUS_BETA: str = "#0047AB"
    STATUS_BETA_CONTAINER: str = "#E3F2FD"
    STATUS_BETA_ON_CONTAINER: str = "#002966"
    STATUS_BETA_TEXT: str = "#0047AB"
    STATUS_ALPHA: str = "#5D4037"
    STATUS_ALPHA_CONTAINER: str = "#FFF8E1"
    STATUS_ALPHA_ON_CONTAINER: str = "#3E2723"
    STATUS_ALPHA_TEXT: str = "#5D4037"
    STATUS_DEPRECATED: str = "#A0522D"
    STATUS_DEPRECATED_CONTAINER: str = "#F5E6D3"
    STATUS_DEPRECATED_ON_CONTAINER: str = "#5D2906"
    STATUS_DEPRECATED_TEXT: str = "#844425"
    CHART_1: str = "#0047AB"
    CHART_2: str = "#4B0082"
    CHART_3: str = "#004D40"
    CHART_4: str = "#5D4037"
    CHART_5: str = "#A0522D"
    CHART_6: str = "#283593"
    CHART_7: str = "#BF5A36"
    CHART_POSITIVE: str = "#004D40"
    CHART_NEGATIVE: str = "#B3261E"
    CHART_NEUTRAL: str = "#55514B"
    CATEGORY_1: str = "#0047AB"
    CATEGORY_2: str = "#4B0082"
    CATEGORY_3: str = "#004D40"
    CATEGORY_4: str = "#5D4037"
    CATEGORY_5: str = "#A0522D"
    CATEGORY_6: str = "#283593"
    CATEGORY_7: str = "#BF5A36"
    BACKGROUND: str = "#F3F3F1"
    FOREGROUND: str = "#373635"
    CARD: str = "#EEEEEC"
    CARD_FOREGROUND: str = "#373635"
    POPOVER: str = "#E0DFDC"
    POPOVER_FOREGROUND: str = "#373635"
    SECONDARY: str = "#E5E4E1"
    SECONDARY_FOREGROUND: str = "#373635"
    DESTRUCTIVE: str = "#B3261E"
    DESTRUCTIVE_FOREGROUND: str = "#FFFFFF"
    DESTRUCTIVE_TEXT: str = "#9F221B"
    OVERLAY_FOREGROUND: str = "#373635"
    ACCENT: str = "#DFE2E2"
    ACCENT_FOREGROUND: str = "#373635"
    BORDER: str = "#E7E5E0"
    INPUT: str = "#FFFFFF"
    SIDEBAR: str = "#EEEEEC"
    SIDEBAR_FOREGROUND: str = "#373635"
    SIDEBAR_PRIMARY: str = "#546E7A"
    SIDEBAR_PRIMARY_FOREGROUND: str = "#FFFFFF"
    SIDEBAR_ACCENT: str = "#E5E4E1"
    SIDEBAR_ACCENT_FOREGROUND: str = "#373635"
    SIDEBAR_BORDER: str = "#E7E5E0"
    SIDEBAR_RING: str = "#0047AB"


@dataclass(frozen=True)
class MziziRolesDark:
    """Colour roles, dark theme."""
    PRIMARY: str = "#C9D2D7"
    PRIMARY_FOREGROUND: str = "#0E0D0C"
    RING: str = "#86DCFF"
    BRAND_ACCENT: str = "#C9D2D7"
    BRAND_ACCENT_FOREGROUND: str = "#0E0D0C"
    APP_ACCENT: str = "#C9D2D7"
    APP_ACCENT_FOREGROUND: str = "#0E0D0C"
    PITCH: str = "#050505"
    VOID: str = "#080807"
    BASE: str = "#0E0D0C"
    SURFACE: str = "#131211"
    CONTAINER: str = "#1E1D1A"
    OVERLAY: str = "#23221F"
    RAISED: str = "#2E2C29"
    SCRIM: str = "rgba(0, 0, 0, 0.6)"
    WASH: str = "#252524"
    MUTED: str = "#050504"
    TEXT_PRIMARY: str = "#E5E5E3"
    TEXT_SECONDARY: str = "#CCCCCA"
    TEXT_TERTIARY: str = "#B3B3B1"
    HERO_TEXT: str = "#FFFFFF"
    MUTED_FOREGROUND: str = "#CCCCCA"
    SUCCESS: str = "#64FFDA"
    WARNING: str = "#FFD866"
    ERROR: str = "#F2B8B5"
    INFO: str = "#00B0FF"
    NEUTRAL: str = "#A09C93"
    OFFLINE: str = "#BA9570"
    SYNCING: str = "#36ABBA"
    DESTRUCTIVE_CONTAINER: str = "#3E1818"
    STATUS_SUCCESS: str = "#64FFDA"
    STATUS_SUCCESS_CONTAINER: str = "#00251A"
    STATUS_SUCCESS_ON_CONTAINER: str = "#A7FFEB"
    STATUS_SUCCESS_TEXT: str = "#64FFDA"
    STATUS_WARNING: str = "#FFD740"
    STATUS_WARNING_CONTAINER: str = "#332200"
    STATUS_WARNING_ON_CONTAINER: str = "#FFECB3"
    STATUS_WARNING_TEXT: str = "#FFD740"
    STATUS_INFO: str = "#00B0FF"
    STATUS_INFO_CONTAINER: str = "#001F3F"
    STATUS_INFO_ON_CONTAINER: str = "#B3E5FC"
    STATUS_INFO_TEXT: str = "#86DCFF"
    STATUS_DANGER: str = "#E1B07E"
    STATUS_DANGER_CONTAINER: str = "#3E2817"
    STATUS_DANGER_ON_CONTAINER: str = "#F5E6D3"
    STATUS_DANGER_TEXT: str = "#EBCCA3"
    STATUS_PREMIUM: str = "#B388FF"
    STATUS_PREMIUM_CONTAINER: str = "#1A0033"
    STATUS_PREMIUM_ON_CONTAINER: str = "#E3C2E8"
    STATUS_PREMIUM_TEXT: str = "#DCC8FF"
    STATUS_NEUTRAL: str = "#A09C93"
    STATUS_NEUTRAL_CONTAINER: str = "#1E1D1A"
    STATUS_NEUTRAL_ON_CONTAINER: str = "#E5E5E3"
    STATUS_NEUTRAL_TEXT: str = "#CCCCCA"
    STATUS_STABLE: str = "#64FFDA"
    STATUS_STABLE_CONTAINER: str = "#00251A"
    STATUS_STABLE_ON_CONTAINER: str = "#A7FFEB"
    STATUS_STABLE_TEXT: str = "#64FFDA"
    STATUS_BETA: str = "#00B0FF"
    STATUS_BETA_CONTAINER: str = "#001F3F"
    STATUS_BETA_ON_CONTAINER: str = "#B3E5FC"
    STATUS_BETA_TEXT: str = "#86DCFF"
    STATUS_ALPHA: str = "#FFD740"
    STATUS_ALPHA_CONTAINER: str = "#332200"
    STATUS_ALPHA_ON_CONTAINER: str = "#FFECB3"
    STATUS_ALPHA_TEXT: str = "#FFD740"
    STATUS_DEPRECATED: str = "#E1B07E"
    STATUS_DEPRECATED_CONTAINER: str = "#3E2817"
    STATUS_DEPRECATED_ON_CONTAINER: str = "#F5E6D3"
    STATUS_DEPRECATED_TEXT: str = "#EBCCA3"
    CHART_1: str = "#00B0FF"
    CHART_2: str = "#B388FF"
    CHART_3: str = "#64FFDA"
    CHART_4: str = "#FFD740"
    CHART_5: str = "#E1B07E"
    CHART_6: str = "#3D5AFE"
    CHART_7: str = "#FF8A65"
    CHART_POSITIVE: str = "#64FFDA"
    CHART_NEGATIVE: str = "#F2B8B5"
    CHART_NEUTRAL: str = "#A09C93"
    CATEGORY_1: str = "#00B0FF"
    CATEGORY_2: str = "#B388FF"
    CATEGORY_3: str = "#64FFDA"
    CATEGORY_4: str = "#FFD740"
    CATEGORY_5: str = "#E1B07E"
    CATEGORY_6: str = "#3D5AFE"
    CATEGORY_7: str = "#FF8A65"
    BACKGROUND: str = "#0E0D0C"
    FOREGROUND: str = "#E5E5E3"
    CARD: str = "#131211"
    CARD_FOREGROUND: str = "#E5E5E3"
    POPOVER: str = "#23221F"
    POPOVER_FOREGROUND: str = "#E5E5E3"
    SECONDARY: str = "#1E1D1A"
    SECONDARY_FOREGROUND: str = "#E5E5E3"
    DESTRUCTIVE: str = "#F3BDBA"
    DESTRUCTIVE_FOREGROUND: str = "#0E0D0C"
    DESTRUCTIVE_TEXT: str = "#F3C0BD"
    OVERLAY_FOREGROUND: str = "#E5E5E3"
    ACCENT: str = "#20201F"
    ACCENT_FOREGROUND: str = "#E5E5E3"
    BORDER: str = "#2A2927"
    INPUT: str = "#100F0E"
    SIDEBAR: str = "#131211"
    SIDEBAR_FOREGROUND: str = "#E5E5E3"
    SIDEBAR_PRIMARY: str = "#C9D2D7"
    SIDEBAR_PRIMARY_FOREGROUND: str = "#0E0D0C"
    SIDEBAR_ACCENT: str = "#1E1D1A"
    SIDEBAR_ACCENT_FOREGROUND: str = "#E5E5E3"
    SIDEBAR_BORDER: str = "#2A2927"
    SIDEBAR_RING: str = "#86DCFF"


@dataclass(frozen=True)
class MziziRoleMetrics:
    """Size and radius roles in pixels, and the font roles' families."""
    SPACING_TOUCH: int = 56
    SPACING_TOUCH_MIN: int = 48
    SPACING_CONTROL: int = 56
    SPACING_CONTROL_SM: int = 48
    SPACING_CONTROL_LG: int = 56
    SPACING_CONTROL_ICON: int = 48
    SPACING_CONTROL_DENSE: int = 32
    SPACING_FIELD: int = 56
    SPACING_FIELD_SM: int = 48
    RADIUS_CONTROL: int = 9999
    RADIUS_FIELD: int = 9999
    RADIUS_BADGE: int = 9999
    RADIUS_CARD: int = 14
    RADIUS_DIALOG: int = 17
    FONT_BODY: str = "Noto Sans"
    FONT_DISPLAY: str = "Noto Serif"
    FONT_CODE: str = "JetBrains Mono"


minerals = MziziMinerals()
heritage = MziziHeritage()
experimental = MziziExperimental()
spacing = MziziSpacing()
radius = MziziRadius()
roles_light = MziziRolesLight()
roles_dark = MziziRolesDark()
role_metrics = MziziRoleMetrics()

# Ordered chart series for matplotlib / plotly / altair — dark theme.
# Minerals then heritage, deliberately: this is a series ordering for plots, not
# a list of the families that exist. The experimental seven are exported above
# as `experimental` and are left out of the default series on purpose — they
# are a heptagon of neighbouring hues, which is a poor categorical scale.
CHART_COLORS = [
    minerals.COBALT_DARK,
    minerals.TANZANITE_DARK,
    minerals.MALACHITE_DARK,
    minerals.GOLD_DARK,
    minerals.TERRACOTTA_DARK,
    minerals.SODALITE_DARK,
    minerals.COPPER_DARK,
    heritage.INDIGO_DARK,
    heritage.SAVANNA_DARK,
    heritage.BAOBAB_DARK,
    heritage.SUNSET_DARK,
    heritage.RIVER_DARK,
    heritage.HEMATITE_DARK,
    heritage.KALAHARI_DARK,
]
