// NYUCHI DESIGN TOKENS — N1
// Kotlin / Jetpack Compose — generated by scripts/sync-tokens.ts from
// lib/tokens/palette.source.ts, the canonical palette in this repo.
//
// Carries all 21 families: seven minerals, seven heritage tones and
// the seven experimental — the same set /v1/brand and the MCP serve.
//
// DO NOT EDIT BY HAND. Run `pnpm tokens:sync`; `pnpm tokens:verify`
// fails the build if this file drifts from the source.

package com.nyuchi.design.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object MziziColors {
    // Seven African Minerals
    val CobaltDark  = Color(0xFF00B0FF)
    val CobaltLight = Color(0xFF0047AB)
    val TanzaniteDark  = Color(0xFFB388FF)
    val TanzaniteLight = Color(0xFF4B0082)
    val MalachiteDark  = Color(0xFF64FFDA)
    val MalachiteLight = Color(0xFF004D40)
    val GoldDark  = Color(0xFFFFD740)
    val GoldLight = Color(0xFF5D4037)
    val TerracottaDark  = Color(0xFFE1B07E)
    val TerracottaLight = Color(0xFFA0522D)
    val SodaliteDark  = Color(0xFF3D5AFE)
    val SodaliteLight = Color(0xFF283593)
    val CopperDark  = Color(0xFFFF8A65)
    val CopperLight = Color(0xFFBF5A36)

    // Seven Heritage Colors
    val IndigoDark  = Color(0xFF7986CB)
    val IndigoLight = Color(0xFF4527A0)
    val SavannaDark  = Color(0xFFE5C158)
    val SavannaLight = Color(0xFF8D6E1A)
    val BaobabDark  = Color(0xFFA1887F)
    val BaobabLight = Color(0xFF4E342E)
    val SunsetDark  = Color(0xFFFF7043)
    val SunsetLight = Color(0xFFD84315)
    val RiverDark  = Color(0xFF4DD0E1)
    val RiverLight = Color(0xFF006064)
    val HematiteDark  = Color(0xFF90A4AE)
    val HematiteLight = Color(0xFF546E7A)
    val KalahariDark  = Color(0xFFE8D9B5)
    val KalahariLight = Color(0xFFC9B589)

    // Seven Experimental tones
    val EmberDark  = Color(0xFFDA8766)
    val EmberLight = Color(0xFF843D20)
    val AcaciaDark  = Color(0xFF93A528)
    val AcaciaLight = Color(0xFF4D5615)
    val FernDark  = Color(0xFF2CB42B)
    val FernLight = Color(0xFF175E17)
    val LagoonDark  = Color(0xFF2AAE9B)
    val LagoonLight = Color(0xFF165B51)
    val StormDark  = Color(0xFF7E9BE0)
    val StormLight = Color(0xFF284CA6)
    val DuskDark  = Color(0xFFBA87E2)
    val DuskLight = Color(0xFF742AAD)
    val ProteaDark  = Color(0xFFDF7BB4)
    val ProteaLight = Color(0xFF932464)
}

object MziziSpacing {
    val xs = 4.dp
    val sm = 8.dp
    val md = 12.dp
    val base = 16.dp
    val lg = 24.dp
    val xl = 32.dp
}

object MziziRadius {
    val sm = 7.dp
    val md = 12.dp
    val lg = 14.dp
    val xl = 17.dp
    val full = 9999.dp
}

object MziziFonts {
    const val sans = "Noto Sans"
    const val serif = "Noto Serif"
    const val mono = "JetBrains Mono"
}

// ─── Roles (#484) ─── what a component names; the Mzizi pack's values.
// From lib/tokens/roles.source.ts. A brand pack maps the same roles to its own values.
object MziziRoles {
    object Light {
        val primary = Color(0xFF546E7A)
        val primaryForeground = Color(0xFFFFFFFF)
        val ring = Color(0xFF0047AB)
        val brandAccent = Color(0xFF546E7A)
        val brandAccentForeground = Color(0xFFFFFFFF)
        val appAccent = Color(0xFF546E7A)
        val appAccentForeground = Color(0xFFFFFFFF)
        val pitch = Color(0xFFFAFAFA)
        val void = Color(0xFFF8F8F7)
        val base = Color(0xFFF3F3F1)
        val surface = Color(0xFFEEEEEC)
        val container = Color(0xFFE5E4E1)
        val overlay = Color(0xFFE0DFDC)
        val raised = Color(0xFFD6D5D1)
        val scrim = Color(0x66000000)
        val wash = Color(0xFFE3E5E4)
        val muted = Color(0xFFFAF9F5)
        val textPrimary = Color(0xFF373635)
        val textSecondary = Color(0xFF575655)
        val textTertiary = Color(0xFF797877)
        val heroText = Color(0xFFFFFFFF)
        val mutedForeground = Color(0xFF575655)
        val success = Color(0xFF004D40)
        val warning = Color(0xFF7A5C00)
        val error = Color(0xFFB3261E)
        val info = Color(0xFF0047AB)
        val neutral = Color(0xFF55514B)
        val offline = Color(0xFF674C32)
        val syncing = Color(0xFF1C5962)
        val destructiveContainer = Color(0xFFFDEDED)
        val statusSuccess = Color(0xFF004D40)
        val statusSuccessContainer = Color(0xFFE0F2F1)
        val statusSuccessOnContainer = Color(0xFF00332B)
        val statusSuccessText = Color(0xFF004D40)
        val statusWarning = Color(0xFF5D4037)
        val statusWarningContainer = Color(0xFFFFF8E1)
        val statusWarningOnContainer = Color(0xFF3E2723)
        val statusWarningText = Color(0xFF5D4037)
        val statusInfo = Color(0xFF0047AB)
        val statusInfoContainer = Color(0xFFE3F2FD)
        val statusInfoOnContainer = Color(0xFF002966)
        val statusInfoText = Color(0xFF0047AB)
        val statusDanger = Color(0xFFA0522D)
        val statusDangerContainer = Color(0xFFF5E6D3)
        val statusDangerOnContainer = Color(0xFF5D2906)
        val statusDangerText = Color(0xFF844425)
        val statusPremium = Color(0xFF4B0082)
        val statusPremiumContainer = Color(0xFFF3E5F5)
        val statusPremiumOnContainer = Color(0xFF2E004D)
        val statusPremiumText = Color(0xFF4B0082)
        val statusNeutral = Color(0xFF55514B)
        val statusNeutralContainer = Color(0xFFE5E4E1)
        val statusNeutralOnContainer = Color(0xFF373635)
        val statusNeutralText = Color(0xFF575655)
        val statusStable = Color(0xFF004D40)
        val statusStableContainer = Color(0xFFE0F2F1)
        val statusStableOnContainer = Color(0xFF00332B)
        val statusStableText = Color(0xFF004D40)
        val statusBeta = Color(0xFF0047AB)
        val statusBetaContainer = Color(0xFFE3F2FD)
        val statusBetaOnContainer = Color(0xFF002966)
        val statusBetaText = Color(0xFF0047AB)
        val statusAlpha = Color(0xFF5D4037)
        val statusAlphaContainer = Color(0xFFFFF8E1)
        val statusAlphaOnContainer = Color(0xFF3E2723)
        val statusAlphaText = Color(0xFF5D4037)
        val statusDeprecated = Color(0xFFA0522D)
        val statusDeprecatedContainer = Color(0xFFF5E6D3)
        val statusDeprecatedOnContainer = Color(0xFF5D2906)
        val statusDeprecatedText = Color(0xFF844425)
        val chart1 = Color(0xFF0047AB)
        val chart2 = Color(0xFF4B0082)
        val chart3 = Color(0xFF004D40)
        val chart4 = Color(0xFF5D4037)
        val chart5 = Color(0xFFA0522D)
        val chart6 = Color(0xFF283593)
        val chart7 = Color(0xFFBF5A36)
        val chartPositive = Color(0xFF004D40)
        val chartNegative = Color(0xFFB3261E)
        val chartNeutral = Color(0xFF55514B)
        val category1 = Color(0xFF0047AB)
        val category2 = Color(0xFF4B0082)
        val category3 = Color(0xFF004D40)
        val category4 = Color(0xFF5D4037)
        val category5 = Color(0xFFA0522D)
        val category6 = Color(0xFF283593)
        val category7 = Color(0xFFBF5A36)
        val background = Color(0xFFF3F3F1)
        val foreground = Color(0xFF373635)
        val card = Color(0xFFEEEEEC)
        val cardForeground = Color(0xFF373635)
        val popover = Color(0xFFE0DFDC)
        val popoverForeground = Color(0xFF373635)
        val secondary = Color(0xFFE5E4E1)
        val secondaryForeground = Color(0xFF373635)
        val destructive = Color(0xFFB3261E)
        val destructiveForeground = Color(0xFFFFFFFF)
        val destructiveText = Color(0xFF9F221B)
        val overlayForeground = Color(0xFF373635)
        val accent = Color(0xFFDFE2E2)
        val accentForeground = Color(0xFF373635)
        val border = Color(0xFFE7E5E0)
        val input = Color(0xFFFFFFFF)
        val sidebar = Color(0xFFEEEEEC)
        val sidebarForeground = Color(0xFF373635)
        val sidebarPrimary = Color(0xFF546E7A)
        val sidebarPrimaryForeground = Color(0xFFFFFFFF)
        val sidebarAccent = Color(0xFFE5E4E1)
        val sidebarAccentForeground = Color(0xFF373635)
        val sidebarBorder = Color(0xFFE7E5E0)
        val sidebarRing = Color(0xFF0047AB)
    }

    object Dark {
        val primary = Color(0xFFC9D2D7)
        val primaryForeground = Color(0xFF0E0D0C)
        val ring = Color(0xFF86DCFF)
        val brandAccent = Color(0xFFC9D2D7)
        val brandAccentForeground = Color(0xFF0E0D0C)
        val appAccent = Color(0xFFC9D2D7)
        val appAccentForeground = Color(0xFF0E0D0C)
        val pitch = Color(0xFF050505)
        val void = Color(0xFF080807)
        val base = Color(0xFF0E0D0C)
        val surface = Color(0xFF131211)
        val container = Color(0xFF1E1D1A)
        val overlay = Color(0xFF23221F)
        val raised = Color(0xFF2E2C29)
        val scrim = Color(0x99000000)
        val wash = Color(0xFF252524)
        val muted = Color(0xFF050504)
        val textPrimary = Color(0xFFE5E5E3)
        val textSecondary = Color(0xFFCCCCCA)
        val textTertiary = Color(0xFFB3B3B1)
        val heroText = Color(0xFFFFFFFF)
        val mutedForeground = Color(0xFFCCCCCA)
        val success = Color(0xFF64FFDA)
        val warning = Color(0xFFFFD866)
        val error = Color(0xFFF2B8B5)
        val info = Color(0xFF00B0FF)
        val neutral = Color(0xFFA09C93)
        val offline = Color(0xFFBA9570)
        val syncing = Color(0xFF36ABBA)
        val destructiveContainer = Color(0xFF3E1818)
        val statusSuccess = Color(0xFF64FFDA)
        val statusSuccessContainer = Color(0xFF00251A)
        val statusSuccessOnContainer = Color(0xFFA7FFEB)
        val statusSuccessText = Color(0xFF64FFDA)
        val statusWarning = Color(0xFFFFD740)
        val statusWarningContainer = Color(0xFF332200)
        val statusWarningOnContainer = Color(0xFFFFECB3)
        val statusWarningText = Color(0xFFFFD740)
        val statusInfo = Color(0xFF00B0FF)
        val statusInfoContainer = Color(0xFF001F3F)
        val statusInfoOnContainer = Color(0xFFB3E5FC)
        val statusInfoText = Color(0xFF86DCFF)
        val statusDanger = Color(0xFFE1B07E)
        val statusDangerContainer = Color(0xFF3E2817)
        val statusDangerOnContainer = Color(0xFFF5E6D3)
        val statusDangerText = Color(0xFFEBCCA3)
        val statusPremium = Color(0xFFB388FF)
        val statusPremiumContainer = Color(0xFF1A0033)
        val statusPremiumOnContainer = Color(0xFFE3C2E8)
        val statusPremiumText = Color(0xFFDCC8FF)
        val statusNeutral = Color(0xFFA09C93)
        val statusNeutralContainer = Color(0xFF1E1D1A)
        val statusNeutralOnContainer = Color(0xFFE5E5E3)
        val statusNeutralText = Color(0xFFCCCCCA)
        val statusStable = Color(0xFF64FFDA)
        val statusStableContainer = Color(0xFF00251A)
        val statusStableOnContainer = Color(0xFFA7FFEB)
        val statusStableText = Color(0xFF64FFDA)
        val statusBeta = Color(0xFF00B0FF)
        val statusBetaContainer = Color(0xFF001F3F)
        val statusBetaOnContainer = Color(0xFFB3E5FC)
        val statusBetaText = Color(0xFF86DCFF)
        val statusAlpha = Color(0xFFFFD740)
        val statusAlphaContainer = Color(0xFF332200)
        val statusAlphaOnContainer = Color(0xFFFFECB3)
        val statusAlphaText = Color(0xFFFFD740)
        val statusDeprecated = Color(0xFFE1B07E)
        val statusDeprecatedContainer = Color(0xFF3E2817)
        val statusDeprecatedOnContainer = Color(0xFFF5E6D3)
        val statusDeprecatedText = Color(0xFFEBCCA3)
        val chart1 = Color(0xFF00B0FF)
        val chart2 = Color(0xFFB388FF)
        val chart3 = Color(0xFF64FFDA)
        val chart4 = Color(0xFFFFD740)
        val chart5 = Color(0xFFE1B07E)
        val chart6 = Color(0xFF3D5AFE)
        val chart7 = Color(0xFFFF8A65)
        val chartPositive = Color(0xFF64FFDA)
        val chartNegative = Color(0xFFF2B8B5)
        val chartNeutral = Color(0xFFA09C93)
        val category1 = Color(0xFF00B0FF)
        val category2 = Color(0xFFB388FF)
        val category3 = Color(0xFF64FFDA)
        val category4 = Color(0xFFFFD740)
        val category5 = Color(0xFFE1B07E)
        val category6 = Color(0xFF3D5AFE)
        val category7 = Color(0xFFFF8A65)
        val background = Color(0xFF0E0D0C)
        val foreground = Color(0xFFE5E5E3)
        val card = Color(0xFF131211)
        val cardForeground = Color(0xFFE5E5E3)
        val popover = Color(0xFF23221F)
        val popoverForeground = Color(0xFFE5E5E3)
        val secondary = Color(0xFF1E1D1A)
        val secondaryForeground = Color(0xFFE5E5E3)
        val destructive = Color(0xFFF3BDBA)
        val destructiveForeground = Color(0xFF0E0D0C)
        val destructiveText = Color(0xFFF3C0BD)
        val overlayForeground = Color(0xFFE5E5E3)
        val accent = Color(0xFF20201F)
        val accentForeground = Color(0xFFE5E5E3)
        val border = Color(0xFF2A2927)
        val input = Color(0xFF100F0E)
        val sidebar = Color(0xFF131211)
        val sidebarForeground = Color(0xFFE5E5E3)
        val sidebarPrimary = Color(0xFFC9D2D7)
        val sidebarPrimaryForeground = Color(0xFF0E0D0C)
        val sidebarAccent = Color(0xFF1E1D1A)
        val sidebarAccentForeground = Color(0xFFE5E5E3)
        val sidebarBorder = Color(0xFF2A2927)
        val sidebarRing = Color(0xFF86DCFF)
    }

    val spacingTouch = 56.dp
    val spacingTouchMin = 48.dp
    val spacingControl = 56.dp
    val spacingControlSm = 48.dp
    val spacingControlLg = 56.dp
    val spacingControlIcon = 48.dp
    val spacingControlDense = 32.dp
    val spacingField = 56.dp
    val spacingFieldSm = 48.dp
    val radiusControl = 9999.dp
    val radiusField = 9999.dp
    val radiusBadge = 9999.dp
    val radiusCard = 14.dp
    val radiusDialog = 17.dp
    const val fontBody = "Noto Sans"
    const val fontDisplay = "Noto Serif"
    const val fontCode = "JetBrains Mono"
}
