// NYUCHI DESIGN TOKENS — N1
// Swift / SwiftUI — generated by scripts/sync-tokens.ts from
// lib/tokens/palette.source.ts, the canonical palette in this repo.
//
// Carries all 21 families: seven minerals, seven heritage tones and
// the seven experimental — the same set /v1/brand and the MCP serve.
//
// DO NOT EDIT BY HAND. Run `pnpm tokens:sync`; `pnpm tokens:verify`
// fails the build if this file drifts from the source.

import SwiftUI

public extension Color {
    // Seven African Minerals
    static let mziziCobaltDark  = Color(hex: "#00B0FF")
    static let mziziCobaltLight = Color(hex: "#0047AB")
    static let mziziTanzaniteDark  = Color(hex: "#B388FF")
    static let mziziTanzaniteLight = Color(hex: "#4B0082")
    static let mziziMalachiteDark  = Color(hex: "#64FFDA")
    static let mziziMalachiteLight = Color(hex: "#004D40")
    static let mziziGoldDark  = Color(hex: "#FFD740")
    static let mziziGoldLight = Color(hex: "#5D4037")
    static let mziziTerracottaDark  = Color(hex: "#E1B07E")
    static let mziziTerracottaLight = Color(hex: "#A0522D")
    static let mziziSodaliteDark  = Color(hex: "#3D5AFE")
    static let mziziSodaliteLight = Color(hex: "#283593")
    static let mziziCopperDark  = Color(hex: "#FF8A65")
    static let mziziCopperLight = Color(hex: "#BF5A36")

    // Seven Heritage Colors
    static let mziziIndigoDark  = Color(hex: "#7986CB")
    static let mziziIndigoLight = Color(hex: "#4527A0")
    static let mziziSavannaDark  = Color(hex: "#E5C158")
    static let mziziSavannaLight = Color(hex: "#8D6E1A")
    static let mziziBaobabDark  = Color(hex: "#A1887F")
    static let mziziBaobabLight = Color(hex: "#4E342E")
    static let mziziSunsetDark  = Color(hex: "#FF7043")
    static let mziziSunsetLight = Color(hex: "#D84315")
    static let mziziRiverDark  = Color(hex: "#4DD0E1")
    static let mziziRiverLight = Color(hex: "#006064")
    static let mziziHematiteDark  = Color(hex: "#90A4AE")
    static let mziziHematiteLight = Color(hex: "#546E7A")
    static let mziziKalahariDark  = Color(hex: "#E8D9B5")
    static let mziziKalahariLight = Color(hex: "#C9B589")

    // Seven Experimental tones
    static let mziziEmberDark  = Color(hex: "#DA8766")
    static let mziziEmberLight = Color(hex: "#843D20")
    static let mziziAcaciaDark  = Color(hex: "#93A528")
    static let mziziAcaciaLight = Color(hex: "#4D5615")
    static let mziziFernDark  = Color(hex: "#2CB42B")
    static let mziziFernLight = Color(hex: "#175E17")
    static let mziziLagoonDark  = Color(hex: "#2AAE9B")
    static let mziziLagoonLight = Color(hex: "#165B51")
    static let mziziStormDark  = Color(hex: "#7E9BE0")
    static let mziziStormLight = Color(hex: "#284CA6")
    static let mziziDuskDark  = Color(hex: "#BA87E2")
    static let mziziDuskLight = Color(hex: "#742AAD")
    static let mziziProteaDark  = Color(hex: "#DF7BB4")
    static let mziziProteaLight = Color(hex: "#932464")
}

public struct MziziSpacing {
    public static let xs: CGFloat = 4
    public static let sm: CGFloat = 8
    public static let md: CGFloat = 12
    public static let base: CGFloat = 16
    public static let lg: CGFloat = 24
    public static let xl: CGFloat = 32
}

public struct MziziRadius {
    public static let sm: CGFloat = 7
    public static let md: CGFloat = 12
    public static let lg: CGFloat = 14
    public static let xl: CGFloat = 17
    public static let full: CGFloat = 9999
}

public struct MziziFonts {
    public static let sans = "Noto Sans"
    public static let serif = "Noto Serif"
    public static let mono = "JetBrains Mono"
}

// ─── Roles (#484) ─── what a component names; the Mzizi pack's values.
// From lib/tokens/roles.source.ts. A brand pack maps the same roles to its own values.
public struct MziziRoles {
    public struct Light {
        public static let primary = Color(hex: "#546E7A")
        public static let primaryForeground = Color(hex: "#FFFFFF")
        public static let ring = Color(hex: "#0047AB")
        public static let brandAccent = Color(hex: "#546E7A")
        public static let brandAccentForeground = Color(hex: "#FFFFFF")
        public static let appAccent = Color(hex: "#546E7A")
        public static let appAccentForeground = Color(hex: "#FFFFFF")
        public static let pitch = Color(hex: "#FAFAFA")
        public static let void = Color(hex: "#F8F8F7")
        public static let base = Color(hex: "#F3F3F1")
        public static let surface = Color(hex: "#EEEEEC")
        public static let container = Color(hex: "#E5E4E1")
        public static let overlay = Color(hex: "#E0DFDC")
        public static let raised = Color(hex: "#D6D5D1")
        public static let scrim = Color.black.opacity(0.4)
        public static let wash = Color(hex: "#E3E5E4")
        public static let muted = Color(hex: "#FAF9F5")
        public static let textPrimary = Color(hex: "#373635")
        public static let textSecondary = Color(hex: "#575655")
        public static let textTertiary = Color(hex: "#797877")
        public static let heroText = Color(hex: "#FFFFFF")
        public static let mutedForeground = Color(hex: "#575655")
        public static let success = Color(hex: "#004D40")
        public static let warning = Color(hex: "#7A5C00")
        public static let error = Color(hex: "#B3261E")
        public static let info = Color(hex: "#0047AB")
        public static let neutral = Color(hex: "#55514B")
        public static let offline = Color(hex: "#674C32")
        public static let syncing = Color(hex: "#1C5962")
        public static let destructiveContainer = Color(hex: "#FDEDED")
        public static let statusSuccess = Color(hex: "#004D40")
        public static let statusSuccessContainer = Color(hex: "#E0F2F1")
        public static let statusSuccessOnContainer = Color(hex: "#00332B")
        public static let statusSuccessText = Color(hex: "#004D40")
        public static let statusWarning = Color(hex: "#5D4037")
        public static let statusWarningContainer = Color(hex: "#FFF8E1")
        public static let statusWarningOnContainer = Color(hex: "#3E2723")
        public static let statusWarningText = Color(hex: "#5D4037")
        public static let statusInfo = Color(hex: "#0047AB")
        public static let statusInfoContainer = Color(hex: "#E3F2FD")
        public static let statusInfoOnContainer = Color(hex: "#002966")
        public static let statusInfoText = Color(hex: "#0047AB")
        public static let statusDanger = Color(hex: "#A0522D")
        public static let statusDangerContainer = Color(hex: "#F5E6D3")
        public static let statusDangerOnContainer = Color(hex: "#5D2906")
        public static let statusDangerText = Color(hex: "#844425")
        public static let statusPremium = Color(hex: "#4B0082")
        public static let statusPremiumContainer = Color(hex: "#F3E5F5")
        public static let statusPremiumOnContainer = Color(hex: "#2E004D")
        public static let statusPremiumText = Color(hex: "#4B0082")
        public static let statusNeutral = Color(hex: "#55514B")
        public static let statusNeutralContainer = Color(hex: "#E5E4E1")
        public static let statusNeutralOnContainer = Color(hex: "#373635")
        public static let statusNeutralText = Color(hex: "#575655")
        public static let statusStable = Color(hex: "#004D40")
        public static let statusStableContainer = Color(hex: "#E0F2F1")
        public static let statusStableOnContainer = Color(hex: "#00332B")
        public static let statusStableText = Color(hex: "#004D40")
        public static let statusBeta = Color(hex: "#0047AB")
        public static let statusBetaContainer = Color(hex: "#E3F2FD")
        public static let statusBetaOnContainer = Color(hex: "#002966")
        public static let statusBetaText = Color(hex: "#0047AB")
        public static let statusAlpha = Color(hex: "#5D4037")
        public static let statusAlphaContainer = Color(hex: "#FFF8E1")
        public static let statusAlphaOnContainer = Color(hex: "#3E2723")
        public static let statusAlphaText = Color(hex: "#5D4037")
        public static let statusDeprecated = Color(hex: "#A0522D")
        public static let statusDeprecatedContainer = Color(hex: "#F5E6D3")
        public static let statusDeprecatedOnContainer = Color(hex: "#5D2906")
        public static let statusDeprecatedText = Color(hex: "#844425")
        public static let chart1 = Color(hex: "#0047AB")
        public static let chart2 = Color(hex: "#4B0082")
        public static let chart3 = Color(hex: "#004D40")
        public static let chart4 = Color(hex: "#5D4037")
        public static let chart5 = Color(hex: "#A0522D")
        public static let chart6 = Color(hex: "#283593")
        public static let chart7 = Color(hex: "#BF5A36")
        public static let chartPositive = Color(hex: "#004D40")
        public static let chartNegative = Color(hex: "#B3261E")
        public static let chartNeutral = Color(hex: "#55514B")
        public static let category1 = Color(hex: "#0047AB")
        public static let category2 = Color(hex: "#4B0082")
        public static let category3 = Color(hex: "#004D40")
        public static let category4 = Color(hex: "#5D4037")
        public static let category5 = Color(hex: "#A0522D")
        public static let category6 = Color(hex: "#283593")
        public static let category7 = Color(hex: "#BF5A36")
        public static let background = Color(hex: "#F3F3F1")
        public static let foreground = Color(hex: "#373635")
        public static let card = Color(hex: "#EEEEEC")
        public static let cardForeground = Color(hex: "#373635")
        public static let popover = Color(hex: "#E0DFDC")
        public static let popoverForeground = Color(hex: "#373635")
        public static let secondary = Color(hex: "#E5E4E1")
        public static let secondaryForeground = Color(hex: "#373635")
        public static let destructive = Color(hex: "#B3261E")
        public static let destructiveForeground = Color(hex: "#FFFFFF")
        public static let destructiveText = Color(hex: "#9F221B")
        public static let overlayForeground = Color(hex: "#373635")
        public static let accent = Color(hex: "#DFE2E2")
        public static let accentForeground = Color(hex: "#373635")
        public static let border = Color(hex: "#E7E5E0")
        public static let input = Color(hex: "#FFFFFF")
        public static let sidebar = Color(hex: "#EEEEEC")
        public static let sidebarForeground = Color(hex: "#373635")
        public static let sidebarPrimary = Color(hex: "#546E7A")
        public static let sidebarPrimaryForeground = Color(hex: "#FFFFFF")
        public static let sidebarAccent = Color(hex: "#E5E4E1")
        public static let sidebarAccentForeground = Color(hex: "#373635")
        public static let sidebarBorder = Color(hex: "#E7E5E0")
        public static let sidebarRing = Color(hex: "#0047AB")
    }

    public struct Dark {
        public static let primary = Color(hex: "#C9D2D7")
        public static let primaryForeground = Color(hex: "#0E0D0C")
        public static let ring = Color(hex: "#86DCFF")
        public static let brandAccent = Color(hex: "#C9D2D7")
        public static let brandAccentForeground = Color(hex: "#0E0D0C")
        public static let appAccent = Color(hex: "#C9D2D7")
        public static let appAccentForeground = Color(hex: "#0E0D0C")
        public static let pitch = Color(hex: "#050505")
        public static let void = Color(hex: "#080807")
        public static let base = Color(hex: "#0E0D0C")
        public static let surface = Color(hex: "#131211")
        public static let container = Color(hex: "#1E1D1A")
        public static let overlay = Color(hex: "#23221F")
        public static let raised = Color(hex: "#2E2C29")
        public static let scrim = Color.black.opacity(0.6)
        public static let wash = Color(hex: "#252524")
        public static let muted = Color(hex: "#050504")
        public static let textPrimary = Color(hex: "#E5E5E3")
        public static let textSecondary = Color(hex: "#CCCCCA")
        public static let textTertiary = Color(hex: "#B3B3B1")
        public static let heroText = Color(hex: "#FFFFFF")
        public static let mutedForeground = Color(hex: "#CCCCCA")
        public static let success = Color(hex: "#64FFDA")
        public static let warning = Color(hex: "#FFD866")
        public static let error = Color(hex: "#F2B8B5")
        public static let info = Color(hex: "#00B0FF")
        public static let neutral = Color(hex: "#A09C93")
        public static let offline = Color(hex: "#BA9570")
        public static let syncing = Color(hex: "#36ABBA")
        public static let destructiveContainer = Color(hex: "#3E1818")
        public static let statusSuccess = Color(hex: "#64FFDA")
        public static let statusSuccessContainer = Color(hex: "#00251A")
        public static let statusSuccessOnContainer = Color(hex: "#A7FFEB")
        public static let statusSuccessText = Color(hex: "#64FFDA")
        public static let statusWarning = Color(hex: "#FFD740")
        public static let statusWarningContainer = Color(hex: "#332200")
        public static let statusWarningOnContainer = Color(hex: "#FFECB3")
        public static let statusWarningText = Color(hex: "#FFD740")
        public static let statusInfo = Color(hex: "#00B0FF")
        public static let statusInfoContainer = Color(hex: "#001F3F")
        public static let statusInfoOnContainer = Color(hex: "#B3E5FC")
        public static let statusInfoText = Color(hex: "#86DCFF")
        public static let statusDanger = Color(hex: "#E1B07E")
        public static let statusDangerContainer = Color(hex: "#3E2817")
        public static let statusDangerOnContainer = Color(hex: "#F5E6D3")
        public static let statusDangerText = Color(hex: "#EBCCA3")
        public static let statusPremium = Color(hex: "#B388FF")
        public static let statusPremiumContainer = Color(hex: "#1A0033")
        public static let statusPremiumOnContainer = Color(hex: "#E3C2E8")
        public static let statusPremiumText = Color(hex: "#DCC8FF")
        public static let statusNeutral = Color(hex: "#A09C93")
        public static let statusNeutralContainer = Color(hex: "#1E1D1A")
        public static let statusNeutralOnContainer = Color(hex: "#E5E5E3")
        public static let statusNeutralText = Color(hex: "#CCCCCA")
        public static let statusStable = Color(hex: "#64FFDA")
        public static let statusStableContainer = Color(hex: "#00251A")
        public static let statusStableOnContainer = Color(hex: "#A7FFEB")
        public static let statusStableText = Color(hex: "#64FFDA")
        public static let statusBeta = Color(hex: "#00B0FF")
        public static let statusBetaContainer = Color(hex: "#001F3F")
        public static let statusBetaOnContainer = Color(hex: "#B3E5FC")
        public static let statusBetaText = Color(hex: "#86DCFF")
        public static let statusAlpha = Color(hex: "#FFD740")
        public static let statusAlphaContainer = Color(hex: "#332200")
        public static let statusAlphaOnContainer = Color(hex: "#FFECB3")
        public static let statusAlphaText = Color(hex: "#FFD740")
        public static let statusDeprecated = Color(hex: "#E1B07E")
        public static let statusDeprecatedContainer = Color(hex: "#3E2817")
        public static let statusDeprecatedOnContainer = Color(hex: "#F5E6D3")
        public static let statusDeprecatedText = Color(hex: "#EBCCA3")
        public static let chart1 = Color(hex: "#00B0FF")
        public static let chart2 = Color(hex: "#B388FF")
        public static let chart3 = Color(hex: "#64FFDA")
        public static let chart4 = Color(hex: "#FFD740")
        public static let chart5 = Color(hex: "#E1B07E")
        public static let chart6 = Color(hex: "#3D5AFE")
        public static let chart7 = Color(hex: "#FF8A65")
        public static let chartPositive = Color(hex: "#64FFDA")
        public static let chartNegative = Color(hex: "#F2B8B5")
        public static let chartNeutral = Color(hex: "#A09C93")
        public static let category1 = Color(hex: "#00B0FF")
        public static let category2 = Color(hex: "#B388FF")
        public static let category3 = Color(hex: "#64FFDA")
        public static let category4 = Color(hex: "#FFD740")
        public static let category5 = Color(hex: "#E1B07E")
        public static let category6 = Color(hex: "#3D5AFE")
        public static let category7 = Color(hex: "#FF8A65")
        public static let background = Color(hex: "#0E0D0C")
        public static let foreground = Color(hex: "#E5E5E3")
        public static let card = Color(hex: "#131211")
        public static let cardForeground = Color(hex: "#E5E5E3")
        public static let popover = Color(hex: "#23221F")
        public static let popoverForeground = Color(hex: "#E5E5E3")
        public static let secondary = Color(hex: "#1E1D1A")
        public static let secondaryForeground = Color(hex: "#E5E5E3")
        public static let destructive = Color(hex: "#F3BDBA")
        public static let destructiveForeground = Color(hex: "#0E0D0C")
        public static let destructiveText = Color(hex: "#F3C0BD")
        public static let overlayForeground = Color(hex: "#E5E5E3")
        public static let accent = Color(hex: "#20201F")
        public static let accentForeground = Color(hex: "#E5E5E3")
        public static let border = Color(hex: "#2A2927")
        public static let input = Color(hex: "#100F0E")
        public static let sidebar = Color(hex: "#131211")
        public static let sidebarForeground = Color(hex: "#E5E5E3")
        public static let sidebarPrimary = Color(hex: "#C9D2D7")
        public static let sidebarPrimaryForeground = Color(hex: "#0E0D0C")
        public static let sidebarAccent = Color(hex: "#1E1D1A")
        public static let sidebarAccentForeground = Color(hex: "#E5E5E3")
        public static let sidebarBorder = Color(hex: "#2A2927")
        public static let sidebarRing = Color(hex: "#86DCFF")
    }

    public static let spacingTouch: CGFloat = 56
    public static let spacingTouchMin: CGFloat = 48
    public static let spacingControl: CGFloat = 56
    public static let spacingControlSm: CGFloat = 48
    public static let spacingControlLg: CGFloat = 56
    public static let spacingControlIcon: CGFloat = 48
    public static let spacingControlDense: CGFloat = 32
    public static let spacingField: CGFloat = 56
    public static let spacingFieldSm: CGFloat = 48
    public static let radiusControl: CGFloat = 9999
    public static let radiusField: CGFloat = 9999
    public static let radiusBadge: CGFloat = 9999
    public static let radiusCard: CGFloat = 14
    public static let radiusDialog: CGFloat = 17
    public static let fontBody = "Noto Sans"
    public static let fontDisplay = "Noto Serif"
    public static let fontCode = "JetBrains Mono"
}
