// NYUCHI DESIGN TOKENS — N1
// Kotlin / Jetpack Compose — generated by scripts/sync-tokens.ts from
// lib/tokens/palette.source.ts, the canonical palette in this repo.
//
// Carries all 21 families: seven minerals, seven heritage tones and
// the seven experimental — the same set /v1/brand and the MCP serve.
//
// DO NOT EDIT BY HAND. Run `pnpm tokens:sync`; `pnpm tokens:verify`
// fails the build if this file drifts from the source.

package com.nyuchi.design.tokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object NyuchiColors {
    // Seven African Minerals
    val CobaltDark  = Color(0xFF00B0FF)
    val CobaltLight = Color(0xFF0047AB)
    val TanzaniteDark  = Color(0xFFB388FF)
    val TanzaniteLight = Color(0xFF4B0082)
    val MalachiteDark  = Color(0xFF64FFDA)
    val MalachiteLight = Color(0xFF004D40)
    val GoldDark  = Color(0xFFFFD740)
    val GoldLight = Color(0xFF5D4037)
    val TerracottaDark  = Color(0xFFE1B07E)
    val TerracottaLight = Color(0xFFA0522D)
    val SodaliteDark  = Color(0xFF3D5AFE)
    val SodaliteLight = Color(0xFF283593)
    val CopperDark  = Color(0xFFFF8A65)
    val CopperLight = Color(0xFFBF5A36)

    // Seven Heritage Colors
    val IndigoDark  = Color(0xFF7986CB)
    val IndigoLight = Color(0xFF4527A0)
    val SavannaDark  = Color(0xFFE5C158)
    val SavannaLight = Color(0xFF8D6E1A)
    val BaobabDark  = Color(0xFFA1887F)
    val BaobabLight = Color(0xFF4E342E)
    val SunsetDark  = Color(0xFFFF7043)
    val SunsetLight = Color(0xFFD84315)
    val RiverDark  = Color(0xFF4DD0E1)
    val RiverLight = Color(0xFF006064)
    val HematiteDark  = Color(0xFF90A4AE)
    val HematiteLight = Color(0xFF546E7A)
    val KalahariDark  = Color(0xFFE8D9B5)
    val KalahariLight = Color(0xFFC9B589)

    // Seven Experimental tones
    val EmberDark  = Color(0xFFDA8766)
    val EmberLight = Color(0xFF843D20)
    val AcaciaDark  = Color(0xFF93A528)
    val AcaciaLight = Color(0xFF4D5615)
    val FernDark  = Color(0xFF2CB42B)
    val FernLight = Color(0xFF175E17)
    val LagoonDark  = Color(0xFF2AAE9B)
    val LagoonLight = Color(0xFF165B51)
    val StormDark  = Color(0xFF7E9BE0)
    val StormLight = Color(0xFF284CA6)
    val DuskDark  = Color(0xFFBA87E2)
    val DuskLight = Color(0xFF742AAD)
    val ProteaDark  = Color(0xFFDF7BB4)
    val ProteaLight = Color(0xFF932464)
}

object NyuchiSpacing {
    val xs = 4.dp
    val sm = 8.dp
    val md = 12.dp
    val base = 16.dp
    val lg = 24.dp
    val xl = 32.dp
}

object NyuchiRadius {
    val sm = 7.dp
    val md = 12.dp
    val lg = 14.dp
    val xl = 17.dp
    val full = 9999.dp
}

object NyuchiFonts {
    const val sans = "Noto Sans"
    const val serif = "Noto Serif"
    const val mono = "JetBrains Mono"
}
