// NYUCHI DESIGN TOKENS — N1
// Swift / SwiftUI — generated by scripts/sync-tokens.ts from
// lib/tokens/palette.source.ts, the canonical palette in this repo.
//
// Carries all 21 families: seven minerals, seven heritage tones and
// the seven experimental — the same set /v1/brand and the MCP serve.
//
// DO NOT EDIT BY HAND. Run `pnpm tokens:sync`; `pnpm tokens:verify`
// fails the build if this file drifts from the source.

import SwiftUI

public extension Color {
    // Seven African Minerals
    static let nyuchiCobaltDark  = Color(hex: "#00B0FF")
    static let nyuchiCobaltLight = Color(hex: "#0047AB")
    static let nyuchiTanzaniteDark  = Color(hex: "#B388FF")
    static let nyuchiTanzaniteLight = Color(hex: "#4B0082")
    static let nyuchiMalachiteDark  = Color(hex: "#64FFDA")
    static let nyuchiMalachiteLight = Color(hex: "#004D40")
    static let nyuchiGoldDark  = Color(hex: "#FFD740")
    static let nyuchiGoldLight = Color(hex: "#5D4037")
    static let nyuchiTerracottaDark  = Color(hex: "#E1B07E")
    static let nyuchiTerracottaLight = Color(hex: "#A0522D")
    static let nyuchiSodaliteDark  = Color(hex: "#3D5AFE")
    static let nyuchiSodaliteLight = Color(hex: "#283593")
    static let nyuchiCopperDark  = Color(hex: "#FF8A65")
    static let nyuchiCopperLight = Color(hex: "#BF5A36")

    // Seven Heritage Colors
    static let nyuchiIndigoDark  = Color(hex: "#7986CB")
    static let nyuchiIndigoLight = Color(hex: "#4527A0")
    static let nyuchiSavannaDark  = Color(hex: "#E5C158")
    static let nyuchiSavannaLight = Color(hex: "#8D6E1A")
    static let nyuchiBaobabDark  = Color(hex: "#A1887F")
    static let nyuchiBaobabLight = Color(hex: "#4E342E")
    static let nyuchiSunsetDark  = Color(hex: "#FF7043")
    static let nyuchiSunsetLight = Color(hex: "#D84315")
    static let nyuchiRiverDark  = Color(hex: "#4DD0E1")
    static let nyuchiRiverLight = Color(hex: "#006064")
    static let nyuchiHematiteDark  = Color(hex: "#90A4AE")
    static let nyuchiHematiteLight = Color(hex: "#546E7A")
    static let nyuchiKalahariDark  = Color(hex: "#E8D9B5")
    static let nyuchiKalahariLight = Color(hex: "#C9B589")

    // Seven Experimental tones
    static let nyuchiEmberDark  = Color(hex: "#DA8766")
    static let nyuchiEmberLight = Color(hex: "#843D20")
    static let nyuchiAcaciaDark  = Color(hex: "#93A528")
    static let nyuchiAcaciaLight = Color(hex: "#4D5615")
    static let nyuchiFernDark  = Color(hex: "#2CB42B")
    static let nyuchiFernLight = Color(hex: "#175E17")
    static let nyuchiLagoonDark  = Color(hex: "#2AAE9B")
    static let nyuchiLagoonLight = Color(hex: "#165B51")
    static let nyuchiStormDark  = Color(hex: "#7E9BE0")
    static let nyuchiStormLight = Color(hex: "#284CA6")
    static let nyuchiDuskDark  = Color(hex: "#BA87E2")
    static let nyuchiDuskLight = Color(hex: "#742AAD")
    static let nyuchiProteaDark  = Color(hex: "#DF7BB4")
    static let nyuchiProteaLight = Color(hex: "#932464")
}

public struct NyuchiSpacing {
    public static let xs: CGFloat = 4
    public static let sm: CGFloat = 8
    public static let md: CGFloat = 12
    public static let base: CGFloat = 16
    public static let lg: CGFloat = 24
    public static let xl: CGFloat = 32
}

public struct NyuchiRadius {
    public static let sm: CGFloat = 7
    public static let md: CGFloat = 12
    public static let lg: CGFloat = 14
    public static let xl: CGFloat = 17
    public static let full: CGFloat = 9999
}

public struct NyuchiFonts {
    public static let sans = "Noto Sans"
    public static let serif = "Noto Serif"
    public static let mono = "JetBrains Mono"
}
