# NYUCHI DESIGN TOKENS — N1
# Python — generated by scripts/sync-tokens.ts from
# lib/tokens/palette.source.ts, the canonical palette in this repo.
#
# Carries all 21 families: seven minerals, seven heritage tones and
# the seven experimental — the same set /v1/brand and the MCP serve.
#
# DO NOT EDIT BY HAND. Run `pnpm tokens:sync`; `pnpm tokens:verify`
# fails the build if this file drifts from the source.

from dataclasses import dataclass


@dataclass(frozen=True)
class NyuchiMinerals:
    """Seven African Minerals — the brand accents, dark and light themes."""
    COBALT_DARK: str = "#00B0FF"
    COBALT_LIGHT: str = "#0047AB"
    TANZANITE_DARK: str = "#B388FF"
    TANZANITE_LIGHT: str = "#4B0082"
    MALACHITE_DARK: str = "#64FFDA"
    MALACHITE_LIGHT: str = "#004D40"
    GOLD_DARK: str = "#FFD740"
    GOLD_LIGHT: str = "#5D4037"
    TERRACOTTA_DARK: str = "#E1B07E"
    TERRACOTTA_LIGHT: str = "#A0522D"
    SODALITE_DARK: str = "#3D5AFE"
    SODALITE_LIGHT: str = "#283593"
    COPPER_DARK: str = "#FF8A65"
    COPPER_LIGHT: str = "#BF5A36"


@dataclass(frozen=True)
class NyuchiHeritage:
    """Seven Heritage tones — atmospheric anchors, dark and light themes."""
    INDIGO_DARK: str = "#7986CB"
    INDIGO_LIGHT: str = "#4527A0"
    SAVANNA_DARK: str = "#E5C158"
    SAVANNA_LIGHT: str = "#8D6E1A"
    BAOBAB_DARK: str = "#A1887F"
    BAOBAB_LIGHT: str = "#4E342E"
    SUNSET_DARK: str = "#FF7043"
    SUNSET_LIGHT: str = "#D84315"
    RIVER_DARK: str = "#4DD0E1"
    RIVER_LIGHT: str = "#006064"
    HEMATITE_DARK: str = "#90A4AE"
    HEMATITE_LIGHT: str = "#546E7A"
    KALAHARI_DARK: str = "#E8D9B5"
    KALAHARI_LIGHT: str = "#C9B589"


@dataclass(frozen=True)
class NyuchiExperimental:
    """Seven Experimental tones — the heptagon, dark and light themes."""
    EMBER_DARK: str = "#DA8766"
    EMBER_LIGHT: str = "#843D20"
    ACACIA_DARK: str = "#93A528"
    ACACIA_LIGHT: str = "#4D5615"
    FERN_DARK: str = "#2CB42B"
    FERN_LIGHT: str = "#175E17"
    LAGOON_DARK: str = "#2AAE9B"
    LAGOON_LIGHT: str = "#165B51"
    STORM_DARK: str = "#7E9BE0"
    STORM_LIGHT: str = "#284CA6"
    DUSK_DARK: str = "#BA87E2"
    DUSK_LIGHT: str = "#742AAD"
    PROTEA_DARK: str = "#DF7BB4"
    PROTEA_LIGHT: str = "#932464"


@dataclass(frozen=True)
class NyuchiSpacing:
    """Spacing scale, in pixels."""
    XS: int = 4
    SM: int = 8
    MD: int = 12
    BASE: int = 16
    LG: int = 24
    XL: int = 32


@dataclass(frozen=True)
class NyuchiRadius:
    """Radius scale, in pixels. Derived from the 7px unit."""
    SM: int = 7
    MD: int = 12
    LG: int = 14
    XL: int = 17
    FULL: int = 9999


minerals = NyuchiMinerals()
heritage = NyuchiHeritage()
experimental = NyuchiExperimental()
spacing = NyuchiSpacing()
radius = NyuchiRadius()

# Ordered chart series for matplotlib / plotly / altair — dark theme.
# Minerals then heritage, deliberately: this is a series ordering for plots, not
# a list of the families that exist. The experimental seven are exported above
# as `experimental` and are left out of the default series on purpose — they
# are a heptagon of neighbouring hues, which is a poor categorical scale.
CHART_COLORS = [
    minerals.COBALT_DARK,
    minerals.TANZANITE_DARK,
    minerals.MALACHITE_DARK,
    minerals.GOLD_DARK,
    minerals.TERRACOTTA_DARK,
    minerals.SODALITE_DARK,
    minerals.COPPER_DARK,
    heritage.INDIGO_DARK,
    heritage.SAVANNA_DARK,
    heritage.BAOBAB_DARK,
    heritage.SUNSET_DARK,
    heritage.RIVER_DARK,
    heritage.HEMATITE_DARK,
    heritage.KALAHARI_DARK,
]
