#!/usr/bin/env node
/**
 * Inline `openapi.yaml` into a module the API can import. `mzizi-api-gateway`
 * bundles it at its registry pin and serves it at `GET /openapi`; the Next.js
 * route described below was removed with the app.
 *
 * The route used to do this:
 *
 *     const yamlPath = join(process.cwd(), "openapi.yaml")
 *     const yaml = await readFile(yamlPath, "utf-8")
 *
 * which is a filesystem read at request time. Cloudflare Workers has no
 * filesystem, so it throws — and the route's `catch` turns any throw into
 * `404 {"error":"OpenAPI specification not found"}`. The spec would simply
 * vanish from the public API, reported as absent rather than as broken.
 *
 * This is the same treatment already given to skills, doctrine, the registry
 * index and registry source. It was missed because those four live in `lib/`
 * and this one lives in `app/api/`, so an inventory of `lib/` could not see it.
 *
 * The artifact is the file's BYTES, not a parsed structure. Emitting parsed
 * YAML would make this a second parser that can disagree with whatever reads
 * the spec — and the route's job is to hand over the document as authored.
 *
 * Usage:
 *   node scripts/generate-openapi.mjs           write the artifact
 *   node scripts/generate-openapi.mjs --check   fail if it is out of date
 */

import { readFileSync, writeFileSync } from "node:fs"
import { join, dirname, relative } from "node:path"
import { fileURLToPath } from "node:url"
import prettier from "prettier"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const SOURCE = join(ROOT, "openapi.yaml")
const OUT = join(ROOT, "lib", "openapi.generated.ts")

/**
 * Format through prettier rather than imitating it.
 *
 * The committed artifact is compared byte-for-byte by `--check`, and the repo
 * also runs `prettier --check` over the tree — so if this emitted anything
 * prettier would rewrite, the two gates could never be green at the same time.
 * That is not hypothetical: the first version of this generator wrote
 * `["GET","OPTIONS"]`, prettier's pre-commit hook rewrote it to
 * `["GET", "OPTIONS"]`, and CI then reported the artifact as out of date with
 * a source that had not changed.
 *
 * Asking prettier is the fix rather than matching its output by hand, because
 * a template that imitates the formatter re-breaks the moment its config
 * changes. Same reasoning as `scripts/sync-tokens.ts` (#262).
 */
async function prettified(filePath, source) {
  const config = await prettier.resolveConfig(filePath)
  return prettier.format(source, { ...config, filepath: filePath })
}

const yaml = readFileSync(SOURCE, "utf8")

const output = await prettified(
  OUT,
  `// GENERATED by scripts/generate-openapi.mjs from openapi.yaml — do not edit.
//
// The OpenAPI document, inlined so \`GET /api/openapi\` can serve it without a
// filesystem. Regenerate with \`pnpm openapi:generate\`; CI runs
// \`pnpm openapi:generate:check\`.

/** \`openapi.yaml\` verbatim, ${yaml.length} bytes. */
export const OPENAPI_YAML = ${JSON.stringify(yaml)}
`
)

if (process.argv.includes("--check")) {
  let current = ""
  try {
    current = readFileSync(OUT, "utf8")
  } catch {
    console.error("✗ lib/openapi.generated.ts is missing. Run `pnpm openapi:generate`.")
    process.exit(1)
  }
  if (current !== output) {
    console.error(
      "✗ lib/openapi.generated.ts is out of date with openapi.yaml. Run `pnpm openapi:generate`."
    )
    process.exit(1)
  }
  console.log(`✓ openapi.yaml in sync — ${yaml.length} bytes`)
} else {
  writeFileSync(OUT, output)
  console.log(`✓ wrote ${relative(ROOT, OUT)} — ${yaml.length} bytes`)
}
