// Generate `lib/skills.generated.ts` from the published skills bundle.
//
// WHY GENERATED RATHER THAN READ AT RUNTIME. The first attempt read
// `@nyuchi/mzizi-skills` through `createRequire(import.meta.url)` inside
// `lib/skills.ts`. It typechecked, every test passed, and `next build` died:
//
//   Error: EBADF: bad file descriptor, read
//   Failed to collect page data for /skills/[name]
//
// Turbopack rewrites `import.meta.url` in the server bundle, so the require it
// creates no longer resolves against the real filesystem. Runtime package
// resolution is not available to this app, and no amount of care in the reader
// changes that.
//
// So the bundle is inlined at build time instead — the same shape as
// `lib/tokens/palette.generated.ts` and the derived fields in `registry.json`:
// a generator, a committed artifact, and a `--check` gate so it cannot drift
// from its source. That is strictly better than a runtime read anyway: the
// content ships with the deployment, so a missing package fails the build
// rather than a request.
//
// Usage:
//   node scripts/generate-skills.mjs           write lib/skills.generated.ts
//   node scripts/generate-skills.mjs --check   fail if stale (CI)

import { readFileSync, writeFileSync, existsSync } from "node:fs"
import { createRequire } from "node:module"
import { join } from "node:path"
import prettier from "prettier"

const require_ = createRequire(import.meta.url)
const OUT = join(process.cwd(), "lib", "skills.generated.ts")
const check = process.argv.includes("--check")

function fail(msg) {
  console.error(`✗ ${msg}`)
  process.exit(1)
}

/** Split YAML frontmatter from the body — the same small reader lib/doctrine.ts uses. */
function splitFrontmatter(raw) {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(raw)
  if (!match) return { fields: {}, body: raw.trim() }
  const fields = {}
  for (const line of match[1].split(/\r?\n/)) {
    const m = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line)
    if (!m) continue
    let value = m[2].trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    fields[m[1]] = value
  }
  return { fields, body: raw.slice(match[0].length).trim() }
}

let indexPath
try {
  indexPath = require_.resolve("@nyuchi/mzizi-skills/index.json")
} catch {
  fail("@nyuchi/mzizi-skills is not installed — run `pnpm install`")
}

const bundle = JSON.parse(readFileSync(indexPath, "utf8"))
if (!Array.isArray(bundle.skills) || bundle.skills.length === 0) {
  fail("@nyuchi/mzizi-skills has no skills")
}

const skills = bundle.skills.map((entry) => {
  const { fields, body } = splitFrontmatter(
    readFileSync(require_.resolve(`@nyuchi/mzizi-skills/${entry.file}`), "utf8")
  )
  // index.json first — it is the description that ships, and applying a fix to
  // the frontmatter alone has already left a stale one in production once.
  const description = entry.description || fields.description || ""
  if (!body) fail(`${entry.file} has an empty body`)
  if (!description) fail(`${entry.name} has no description`)
  return {
    name: fields.name || entry.name,
    description,
    body_mdx: body,
    source: `mzizi-dev/agent-tools/mzizi-skills/${entry.file.replace(/\/SKILL\.md$/, "")}`,
  }
})

const rawContent = `/**
 * GENERATED by scripts/generate-skills.mjs — do not edit.
 *
 * The skills this deployment serves, inlined from \`@nyuchi/mzizi-skills\` at
 * build time. There is no database copy and no sync step: bumping the package
 * is a commit, and the commit is what changes what agents read.
 *
 * Regenerate with \`pnpm skills:generate\`; \`pnpm skills:generate:check\` is the
 * CI gate that fails when this file and the installed package disagree.
 */

export interface GeneratedSkill {
  name: string
  description: string
  body_mdx: string
  source: string
}

export const SKILLS_VERSION = ${JSON.stringify(bundle.version)}

export const SKILLS: readonly GeneratedSkill[] = ${JSON.stringify(skills, null, 2)}
`

// Format with the repo's own Prettier config before writing.
//
// Not cosmetic: `lint / prettier` runs `--check` over the tree, so an
// unformatted generated file fails CI on every regeneration — and hand-fixing
// it only works until the next `skills:generate`. Formatting here is what makes
// the generator and the formatter agree permanently, and it keeps the `--check`
// comparison below meaningful rather than perpetually false.
const prettierConfig = await prettier.resolveConfig(OUT)
const content = await prettier.format(rawContent, { ...prettierConfig, filepath: OUT })

if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : ""
  if (current !== content) {
    fail(
      "lib/skills.generated.ts is stale against @nyuchi/mzizi-skills. " +
        "Run `pnpm skills:generate` and commit the result."
    )
  }
  console.log(`✓ generated skills match the package (${skills.length} skills, v${bundle.version})`)
} else {
  writeFileSync(OUT, content)
  console.log(`✓ wrote lib/skills.generated.ts — ${skills.length} skills, v${bundle.version}`)
}
