/**
 * CROSS-SURFACE FAMILY PARITY.
 *
 * Mzizi publishes its design tokens through three distribution surfaces — the
 * MCP server and `/v1/brand`, the shadcn registry, and the crates registry —
 * and those surfaces are supposed to carry the same palette. For most of this
 * repo's life they did not, and nothing said so.
 *
 * The specific failure: `generateCSSVariables()` in the TypeScript token file
 * carried two literal arrays, five minerals and five heritage tones, written
 * when the palette was five-and-five. The palette grew to seven-and-seven, then
 * gained the experimental seven. The arrays did not move. A consumer installing
 * `nyuchi-tokens-typescript` got ten of twenty-one families; a consumer reading
 * `/v1/brand` got all twenty-one; and `sodalite` did not appear anywhere in the
 * TypeScript file at all. The six generated platform files had a narrower
 * version of the same hole — seven and seven, but no experimental.
 *
 * WHY THE EXISTING GATES DID NOT CATCH IT, which is the part worth keeping:
 *
 *   - `pnpm tokens:verify` (scripts/sync-tokens.ts --check) is a real gate, and
 *     it does fail the build on drift — but only for the artifacts it writes.
 *     `nyuchi-tokens-typescript.ts` is not one of them. It compared six files
 *     against the source and was silent about the seventh, which was the one
 *     that was wrong.
 *   - `__tests__/tokens-seven-fold.test.ts` asserts the counts, but against
 *     `palette.generated.ts` and `app/globals.css` — the two artifacts that were
 *     already correct. It never looked at an emitter.
 *
 * Both gates were pointed at the source and at the surfaces nearest it. The
 * divergence lived at the far end. So this file walks the far end: it reads the
 * canonical palette, then reads all SEVEN emitters as a consumer would — as
 * text, in the language each one is published in — and asserts they agree with
 * it. Adding a family to the palette, or changing a hex, without running
 * `pnpm tokens:sync` fails here naming the surface and the value.
 *
 * IT NOW ASSERTS THE HEXES, NOT ONLY THE FAMILY NAMES. When this file was
 * written it checked presence only, and recorded why: six families in
 * `nyuchi-tokens-typescript.ts` — terracotta, indigo, savanna, baobab, sunset
 * and river — carried pre-Seven values (baobab was `#A5D6A7`, a green, where
 * the palette says `#A1887F`, a brown), and correcting a published surface was
 * held to be a separate decision from closing a presence gap. That decision has
 * been taken. The six are no longer typed at all: the palette region of that
 * file is generated by `scripts/sync-tokens.ts` between
 * `tokens:generated:ts-palette` markers, exactly as the palette regions of
 * `app/globals.css` are, so there is nothing left to hand-correct and nothing
 * left to drift.
 *
 * A presence-only check would not have caught what replaced the presence gap,
 * which is the argument for widening it here rather than trusting the
 * generator. A generator with no failing test is the same trap one layer down:
 * `pnpm tokens:verify` proves the emitters match the source, and this proves it
 * independently, by reading the published bytes rather than by re-running the
 * renderer that produced them.
 */

import { describe, expect, it } from "vitest"
import { readFileSync } from "node:fs"
import { join } from "node:path"
import { experimentalColors, heritageColors, minerals } from "@/lib/tokens/palette.source"
import {
  paletteFamilies,
  primitives,
} from "@/components/registry/n1-tokens/nyuchi-tokens-typescript"

const N1 = join(process.cwd(), "components/registry/n1-tokens")
const read = (file: string) => readFileSync(join(N1, file), "utf8")

/** The canonical family set, from the one file where a colour is authored. */
const EXPECTED = {
  mineral: minerals.map((m) => m.name),
  heritage: heritageColors.map((h) => h.name),
  experimental: experimentalColors.map((e) => e.name),
}
const EXPECTED_ALL = [...EXPECTED.mineral, ...EXPECTED.heritage, ...EXPECTED.experimental].sort()

/**
 * `{ "baobab:dark": "#A1887F", "baobab:light": "#4E342E", … }` — the palette's
 * own answer for every family in both themes, which is what each emitter is
 * compared against below.
 */
const EXPECTED_HEXES: Record<string, string> = Object.fromEntries(
  [...minerals, ...heritageColors, ...experimentalColors].flatMap((c) => [
    [`${c.name}:dark`, c.darkHex.toUpperCase()],
    [`${c.name}:light`, c.lightHex.toUpperCase()],
  ])
)

/** The six that carried pre-Seven values until the palette region was generated. */
const ONCE_DIVERGED = ["terracotta", "indigo", "savanna", "baobab", "sunset", "river"]

/**
 * Pull family names out of an emitter by matching its dark-theme declaration.
 *
 * Matching the emitted SYNTAX rather than reading a structured export is the
 * point: it is what a Swift or Kotlin consumer actually compiles against, and
 * it cannot be satisfied by a file that merely mentions the name in a comment.
 */
const sorted = (names: string[]) => [...new Set(names)].sort()
function scan(source: string, pattern: RegExp, normalise: (s: string) => string): string[] {
  return sorted([...source.matchAll(pattern)].map((m) => normalise(m[1])))
}
const lowerFirst = (s: string) => s.charAt(0).toLowerCase() + s.slice(1)

/**
 * Read `family:theme -> hex` back out of an emitter, the same way: by matching
 * the declaration a consumer compiles against.
 *
 * The hex lands in the LAST capture group and the family name in the first, so
 * one helper serves six syntaxes. Kotlin writes `0xFFRRGGBB` rather than
 * `#RRGGBB`, hence the `#` is added rather than captured.
 */
function scanHexes(
  source: string,
  pattern: RegExp,
  normalise: (s: string) => string
): Record<string, string> {
  const out: Record<string, string> = {}
  for (const m of source.matchAll(pattern)) {
    const name = normalise(m[1])
    const theme = m[2].toLowerCase()
    const hex = m[3].startsWith("#") ? m[3] : `#${m[3]}`
    out[`${name}:${theme}`] = hex.toUpperCase()
  }
  return out
}

/** Every emitter, and how to read the family set and the hexes back out of it. */
const EMITTERS: {
  name: string
  file: string
  families: () => string[]
  hexes: () => Record<string, string>
}[] = [
  {
    name: "swift",
    file: "nyuchi-tokens-swift.swift",
    // static let nyuchiEmberDark  = Color(hex: "#DA8766")
    families: () =>
      scan(read("nyuchi-tokens-swift.swift"), /static let nyuchi(\w+?)Dark\b/g, lowerFirst),
    hexes: () =>
      scanHexes(
        read("nyuchi-tokens-swift.swift"),
        /static let nyuchi(\w+?)(Dark|Light)\s*=\s*Color\(hex:\s*"(#[0-9A-Fa-f]{6})"\)/g,
        lowerFirst
      ),
  },
  {
    name: "kotlin",
    file: "nyuchi-tokens-kotlin.kt",
    // val EmberDark  = Color(0xFFDA8766)
    families: () =>
      scan(read("nyuchi-tokens-kotlin.kt"), /val (\w+?)Dark\s*=\s*Color\(/g, lowerFirst),
    hexes: () =>
      scanHexes(
        read("nyuchi-tokens-kotlin.kt"),
        /val (\w+?)(Dark|Light)\s*=\s*Color\(0xFF([0-9A-Fa-f]{6})\)/g,
        lowerFirst
      ),
  },
  {
    name: "arkts",
    file: "nyuchi-tokens-arkts.ets",
    // emberDark: "#DA8766",
    families: () => scan(read("nyuchi-tokens-arkts.ets"), /(\w+?)Dark:\s*"#/g, (s) => s),
    hexes: () =>
      scanHexes(
        read("nyuchi-tokens-arkts.ets"),
        /(\w+?)(Dark|Light):\s*"(#[0-9A-Fa-f]{6})"/g,
        (s) => s
      ),
  },
  {
    name: "react-native",
    file: "nyuchi-tokens-react-native.ts",
    families: () => scan(read("nyuchi-tokens-react-native.ts"), /(\w+?)Dark:\s*"#/g, (s) => s),
    hexes: () =>
      scanHexes(
        read("nyuchi-tokens-react-native.ts"),
        /(\w+?)(Dark|Light):\s*"(#[0-9A-Fa-f]{6})"/g,
        (s) => s
      ),
  },
  {
    name: "python",
    file: "nyuchi-tokens-python.py",
    // EMBER_DARK: str = "#DA8766"
    families: () =>
      scan(read("nyuchi-tokens-python.py"), /(\w+?)_DARK:\s*str\s*=/g, (s) => s.toLowerCase()),
    hexes: () =>
      scanHexes(
        read("nyuchi-tokens-python.py"),
        /(\w+?)_(DARK|LIGHT):\s*str\s*=\s*"(#[0-9A-Fa-f]{6})"/g,
        (s) => s.toLowerCase()
      ),
  },
  {
    name: "rust",
    file: "nyuchi-tokens-rust.rs",
    // pub const EMBER_DARK: &str = "#DA8766";
    families: () =>
      scan(read("nyuchi-tokens-rust.rs"), /pub const (\w+?)_DARK:\s*&str/g, (s) => s.toLowerCase()),
    hexes: () =>
      scanHexes(
        read("nyuchi-tokens-rust.rs"),
        /pub const (\w+?)_(DARK|LIGHT):\s*&str\s*=\s*"(#[0-9A-Fa-f]{6})";/g,
        (s) => s.toLowerCase()
      ),
  },
  {
    name: "typescript",
    file: "nyuchi-tokens-typescript.ts",
    // Asked through the module's own derivation, so a regression in
    // `paletteFamilies()` — the function `generateCSSVariables()` depends on —
    // fails here rather than passing on the strength of the raw table.
    families: () => sorted(paletteFamilies().map(([name]) => name)),
    // Asked through the module's own table, the way a consumer reads it:
    // `primitives.color.baobab.value` is what an installed copy compiles
    // against, whatever the file looks like around it.
    hexes: () => {
      const palette = primitives.color as Record<string, { value: string } | undefined>
      return Object.fromEntries(
        paletteFamilies().flatMap(([name]) => [
          [`${name}:dark`, palette[name]!.value.toUpperCase()],
          [`${name}:light`, palette[`${name}Light`]!.value.toUpperCase()],
        ])
      )
    },
  },
]

describe("every token emitter carries the canonical family set", () => {
  it("covers all seven emitters", () => {
    // A parity suite that quietly stops covering a surface is worse than none:
    // it reports green for six files while the seventh drifts. This is the
    // guard on the guard.
    expect(EMITTERS.map((e) => e.name).sort()).toEqual([
      "arkts",
      "kotlin",
      "python",
      "react-native",
      "rust",
      "swift",
      "typescript",
    ])
  })

  it("agrees with the palette on how many families exist", () => {
    expect(EXPECTED.mineral).toHaveLength(7)
    expect(EXPECTED.heritage).toHaveLength(7)
    expect(EXPECTED.experimental).toHaveLength(7)
    expect(EXPECTED_ALL).toHaveLength(21)
  })

  for (const emitter of EMITTERS) {
    describe(emitter.name, () => {
      it(`declares exactly the 21 families in lib/tokens/palette.source.ts`, () => {
        // toEqual on the sorted sets, rather than a length check or a series of
        // `toContain`s, so the failure message prints both the missing families
        // and any the emitter invented.
        expect(emitter.families(), `${emitter.file} diverged from the palette`).toEqual(
          EXPECTED_ALL
        )
      })

      for (const [group, names] of Object.entries(EXPECTED)) {
        it(`carries all seven ${group} families`, () => {
          const have = emitter.families()
          const missing = names.filter((n) => !have.includes(n))
          expect(missing, `${emitter.file} is missing ${group}: ${missing.join(", ")}`).toEqual([])
        })
      }

      it("carries the palette's hex for every family, in both themes", () => {
        // toEqual on the whole map rather than 42 assertions: the failure
        // message then prints every value that moved side by side with what the
        // palette says, which is what you need to tell "the source changed and
        // nobody ran tokens:sync" from "someone hand-edited one hex".
        expect(emitter.hexes(), `${emitter.file} diverged from the palette`).toEqual(EXPECTED_HEXES)
      })

      it("carries the canonical hex for the six that once did not", () => {
        // terracotta, indigo, savanna, baobab, sunset and river were pre-Seven
        // in `nyuchi-tokens-typescript.ts` — baobab a green against a brown —
        // and the assertion above would report that as one large diff. Naming
        // them makes a regression read as "baobab is #A5D6A7 again".
        const have = emitter.hexes()
        for (const name of ONCE_DIVERGED) {
          for (const theme of ["dark", "light"]) {
            expect(
              have[`${name}:${theme}`],
              `${emitter.file}: ${name} (${theme}) is not the palette's value`
            ).toBe(EXPECTED_HEXES[`${name}:${theme}`])
          }
        }
      })
    })
  }

  it("names sodalite in every emitter", () => {
    // sodalite is the canary. It appeared ZERO times in the TypeScript token
    // file, and it is the family whose absence proved the five-name arrays were
    // still live rather than merely untidy. Asserted by name so a regression
    // reads as "sodalite is gone from kotlin", not "expected 21, got 20".
    for (const emitter of EMITTERS) {
      expect(emitter.families(), `${emitter.file} is missing sodalite`).toContain("sodalite")
    }
  })
})

describe("the derived family list", () => {
  it("tags each family with the group it belongs to", () => {
    const byName = new Map(paletteFamilies())
    for (const [group, names] of Object.entries(EXPECTED)) {
      for (const name of names) {
        expect(byName.get(name), `${name} should be tagged "${group}"`).toBe(group)
      }
    }
  })

  it("is derived from the token data, not from a literal list", () => {
    // The regression this forbids is precise: someone "fixes" a future gap by
    // pasting the current family names back into generateCSSVariables. That
    // passes every assertion above on the day it is written and rots exactly as
    // the five-name arrays did. Deriving the keys is the fix; a longer literal
    // is the bug wearing a bigger coat.
    const source = readFileSync(join(N1, "nyuchi-tokens-typescript.ts"), "utf8")
    const fn = source.match(/export function generateCSSVariables\(([\s\S]*?)\n\}/)
    expect(fn, "could not locate generateCSSVariables").not.toBeNull()
    // Comments are stripped first, and that distinction matters: the comment
    // inside that function QUOTES the retired five-name arrays in order to
    // explain why they are gone. A citation of a bad pattern is worth keeping;
    // a use of it is not, and a regex cannot tell them apart unless the
    // comments are removed. (`__tests__/tokens-seven-fold.test.ts` reaches the
    // same conclusion about the retired palette name, for the same reason.)
    const body = fn![1].replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\n]*/g, "")
    for (const name of EXPECTED_ALL) {
      expect(
        body.includes(`"${name}"`),
        `generateCSSVariables names "${name}" literally — derive it from primitives.color instead`
      ).toBe(false)
    }
  })
})

/**
 * The palette region of the TypeScript emitter is GENERATED, and this is the
 * guard that keeps it that way.
 *
 * The hex assertions above prove today's values are right. They do not prove
 * the values are derived, and that distinction is the whole lesson of this
 * file: the emitter was correct about family names for exactly as long as it
 * took someone to hand-type a longer list, and correct about hexes never. A
 * value inside the markers is rewritten by `pnpm tokens:sync` and gated by
 * `pnpm tokens:verify`; the identical value typed ten lines below the end
 * marker is gated by nothing.
 */
describe("the generated palette region", () => {
  const SOURCE = readFileSync(join(N1, "nyuchi-tokens-typescript.ts"), "utf8")
  const START = "/* tokens:generated:ts-palette:start */"
  const END = "/* tokens:generated:ts-palette:end */"

  it("is delimited by the markers scripts/sync-tokens.ts writes between", () => {
    // Without both markers the generator hard-fails rather than writing the
    // wrong bytes — but it only runs when someone runs it, and this runs in CI.
    expect(SOURCE.includes(START), "the ts-palette start marker is gone").toBe(true)
    expect(SOURCE.indexOf(END)).toBeGreaterThan(SOURCE.indexOf(START))
  })

  it("holds every one of the 21 families", () => {
    const region = SOURCE.slice(SOURCE.indexOf(START), SOURCE.indexOf(END))
    for (const name of EXPECTED_ALL) {
      expect(
        new RegExp(`\\n\\s*${name}: \\{`).test(region),
        `${name} is declared outside the generated region — move it inside, or it drifts`
      ).toBe(true)
    }
  })

  it("is the only place the palette hexes are written", () => {
    // Outside the region, a palette colour is REFERENCED
    // (`primitives.color.baobab.value`), never restated. Seventeen copies of
    // seven mineral hexes lived in `brandOverrides`, ten more in the chart
    // fallbacks, and ten in `listingThemes`; `circles` and every chart fallback
    // still named terracotta's pre-Seven `#D4A574` after the palette had moved.
    const outside =
      SOURCE.slice(0, SOURCE.indexOf(START)) + SOURCE.slice(SOURCE.indexOf(END) + END.length)
    // Comments cite retired hexes on purpose, to record what they were, so they
    // are stripped first — the same distinction `generateCSSVariables` needs.
    const code = outside.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\n]*/g, "")
    const offenders = Object.entries(EXPECTED_HEXES)
      .filter(([, hex]) => code.toUpperCase().includes(hex))
      .map(([key]) => key)
    expect(
      offenders,
      `palette hexes are hand-written outside the generated region: ${offenders.join(", ")}`
    ).toEqual([])
  })
})
