"""Mzizi resilience for Python (mzizi-dev/mzizi-registry#472).

The public API. The modules beside this file are GENERATED copies of the registry's
``components/registry/n5-resilience/*.py`` and ``n8-assurance/*.py``; this file is the one
hand-written module and only re-exports them. ``tests/test_package.py`` fails if a module's
``__all__`` is not re-exported here.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

from .bulkhead import Bulkhead, BulkheadConfig, BulkheadCore, BulkheadMetrics, Entry
from .chaos import (
    MALFORMED_MARKER,
    ChaosConfig,
    ChaosDecision,
    ChaosEngine,
    Fault,
    FaultKind,
    chaos_middleware,
    chaos_wrap,
    create_chaos,
    is_production_environment,
    with_chaos,
)
from .circuit_breaker import (
    Acquire,
    CircuitBreaker,
    CircuitBreakerConfig,
    CircuitBreakerCore,
    CircuitState,
    Transition,
    breakers,
    get_breaker,
    reset_breakers,
)
from .fallback_chain import FallbackResult, Stage, with_fallback, with_fallback_result
from .mzizi_resilience import (
    HealthMonitor,
    HealthReport,
    HealthStatus,
    Resilience,
    ResilienceConfig,
    ResilienceResult,
    Source,
    health_monitor,
    system_health,
)
from .observability import (
    REDACT_KEYS,
    REDACTED,
    LogEvent,
    Logger,
    LogLevel,
    Sink,
    console_sink,
    create_logger,
    default_sinks,
    log,
    logging_sink,
    measure,
    memory_sink,
    redact,
    set_default_sinks,
    track_error,
)
from .rate_limiter import RateLimitAcquire, RateLimiter, RateLimiterConfig, RateLimiterCore
from .resilience_errors import (
    AllStagesFailedError,
    BulkheadFullError,
    BulkheadQueueTimeoutError,
    ChaosError,
    ChaosForbiddenError,
    CircuitOpenError,
    Clock,
    MalformedPayloadError,
    Mulberry32,
    Random,
    RateLimitExceededError,
    ResilienceConfigError,
    ResilienceError,
    RetriesExhaustedError,
    Sleep,
    StageError,
    SystemClock,
    SystemRandom,
    TimeoutError,
    VirtualClock,
    asyncio_sleep,
    error_code,
    is_rejection,
    mulberry32,
    probability_threshold,
)
from .retry import Jitter, RetryConfig, default_retry_if, retry, retry_delay
from .timeout import simulate_timeout, with_timeout

try:
    __version__ = version("mzizi-resilience")
except PackageNotFoundError:  # running from a source checkout that is not installed
    __version__ = "0.0.0"

__all__ = [
    "MALFORMED_MARKER",
    "REDACTED",
    "REDACT_KEYS",
    "Acquire",
    "AllStagesFailedError",
    "Bulkhead",
    "BulkheadConfig",
    "BulkheadCore",
    "BulkheadFullError",
    "BulkheadMetrics",
    "BulkheadQueueTimeoutError",
    "ChaosConfig",
    "ChaosDecision",
    "ChaosEngine",
    "ChaosError",
    "ChaosForbiddenError",
    "CircuitBreaker",
    "CircuitBreakerConfig",
    "CircuitBreakerCore",
    "CircuitOpenError",
    "CircuitState",
    "Clock",
    "Entry",
    "FallbackResult",
    "Fault",
    "FaultKind",
    "HealthMonitor",
    "HealthReport",
    "HealthStatus",
    "Jitter",
    "LogEvent",
    "LogLevel",
    "Logger",
    "MalformedPayloadError",
    "Mulberry32",
    "Random",
    "RateLimitAcquire",
    "RateLimitExceededError",
    "RateLimiter",
    "RateLimiterConfig",
    "RateLimiterCore",
    "Resilience",
    "ResilienceConfig",
    "ResilienceConfigError",
    "ResilienceError",
    "ResilienceResult",
    "RetriesExhaustedError",
    "RetryConfig",
    "Sink",
    "Sleep",
    "Source",
    "Stage",
    "StageError",
    "SystemClock",
    "SystemRandom",
    "TimeoutError",
    "Transition",
    "VirtualClock",
    "__version__",
    "asyncio_sleep",
    "breakers",
    "chaos_middleware",
    "chaos_wrap",
    "console_sink",
    "create_chaos",
    "create_logger",
    "default_retry_if",
    "default_sinks",
    "error_code",
    "get_breaker",
    "health_monitor",
    "is_production_environment",
    "is_rejection",
    "log",
    "logging_sink",
    "measure",
    "memory_sink",
    "mulberry32",
    "probability_threshold",
    "redact",
    "reset_breakers",
    "retry",
    "retry_delay",
    "set_default_sinks",
    "simulate_timeout",
    "system_health",
    "track_error",
    "with_chaos",
    "with_fallback",
    "with_fallback_result",
    "with_timeout",
]
